/*******************************************************
 文件：CAlgResult.idl
 作者：sharkls
 描述：描述所有算法结果的统一结构
 版本：v1.0
 日期：2025-04-18
 *******************************************************/

#include "CMultiModalSrcData.idl"

// 人体关键点信息
struct Keypoint
{
    float x;
    float y;
    float confidence;
};

// 本帧中所有目标的信息
struct CObjectResult {
    // 融合感知结果信息
    string                   strClass;       // 目标类型（伤员和非伤员）
    octet                    ucSource;       // 数据来源，0无数据，1可见光，2红外，3毫米波，4红外和可见光融合，5三者融合

    // 3D位置信息
    unsigned short           usPcTargetId;   // 3d跟踪的id
    short                    sXCoord;        // X轴坐标：cm
    short                    sYCoord;        // Y轴坐标：cm
    short                    sZCoord;        // Z轴坐标：cm
    unsigned short           usLength;       // 长度：cm
    unsigned short           usWidth;        // 宽度：cm
    unsigned short           usHeight;       // 高度：cm
    short                    sCourseAngle;   // 航向角，度
    float                    fDistance;      // 目标到设备的距离: cm

    // 2D目标框信息
    unsigned short           usVideoTargetId; // 2d跟踪的id
    float                    fVideoConfidence;// 图像检测置信度，范围为0到100
    float                    fTopLeftX;       // 左上角像素点
    float                    fTopLeftY;       // 左上角像素点
    float                    fBottomRightX;   // 右下角像素点
    float                    fBottomRightY;   // 右下角像素点
    octet                    ucColor;         // 颜色
    sequence<Keypoint, 20> vecKeypoints;      // 人体关键点信息（新增）

    // 跟踪结果相关信息
    unsigned short           usTargetId;      // 跟踪结果目标ID
    short                    sSpeed;          // 速度：cm/s
    unsigned long long       ulFirstOccurTime;// 目标首次出现的时间戳
    unsigned long            uiTimeSinceUpdate;
    unsigned short           usHitNum;        // 击打次数
    boolean                  bDeleteFlag;     // 是否删除该轨迹
    unsigned short           usLifeCycle;     // 生命周期
    unsigned short 	         ucSignFlag;	  // 坐标符号标识
    unsigned short	         usVideoInfo[20]; // 点云目标框相关信息
    unsigned short           usMissFrame;     // 丢失帧数
    unsigned short           usFrame;         // 目标帧号（测试使用）
    unsigned short           usLidarFrame;    // 目标帧号（测试使用）

    // 毫米波特有的结果信息
    float                    fSpeedX;         //X方向速度
    float                    fSpeedY;         //Y方向速度
    float                    fAcceleration;   //加速度
    float                    fRCS;            //目标散射面积dbm2
};

// 该传感器在该帧的信息，点云和融合是单帧结果，图像是单张图像的结果
struct CFrameResult : CDataBase {
    sequence<CObjectResult>  vecObjectResult;         // 该帧中所有的参与者信息
    CDisparityResult         tCameraSupplement;       // 相机附加信息
    sequence<CVideoSrcData>  vecVideoSrcData;         // 目标抠图后的图像信息
    // CRadarSupplement         tRadarSupplement;     // 毫米波附加信息
    // CFusionSupplemet         tFusionSupplement;    // 融合附加信息
};



// 算法结果通用的结构体
struct CAlgResult : CDataBase {
    sequence<CFrameResult>   vecFrameResult;        // 表示该传感器在该帧所有的结果，点云和融合是单帧结果，图像是所有图像的结果
};
