// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: BinocularPositioning_conf.proto
// Protobuf C++ Version: 5.30.0-dev

#ifndef BinocularPositioning_5fconf_2eproto_2epb_2eh
#define BinocularPositioning_5fconf_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5030000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "AlgorithmConfig_conf.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_BinocularPositioning_5fconf_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_BinocularPositioning_5fconf_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_BinocularPositioning_5fconf_2eproto;
}  // extern "C"
namespace binocularpositioning {
class BinocularPositioningConfig;
struct BinocularPositioningConfigDefaultTypeInternal;
extern BinocularPositioningConfigDefaultTypeInternal _BinocularPositioningConfig_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull BinocularPositioningConfig_class_data_;
class CRLConfig;
struct CRLConfigDefaultTypeInternal;
extern CRLConfigDefaultTypeInternal _CRLConfig_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull CRLConfig_class_data_;
class ModelConfig;
struct ModelConfigDefaultTypeInternal;
extern ModelConfigDefaultTypeInternal _ModelConfig_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull ModelConfig_class_data_;
class SGBMConfig;
struct SGBMConfigDefaultTypeInternal;
extern SGBMConfigDefaultTypeInternal _SGBMConfig_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull SGBMConfig_class_data_;
}  // namespace binocularpositioning
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace binocularpositioning {

// ===================================================================


// -------------------------------------------------------------------

class SGBMConfig final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:binocularpositioning.SGBMConfig) */ {
 public:
  inline SGBMConfig() : SGBMConfig(nullptr) {}
  ~SGBMConfig() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(SGBMConfig* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(SGBMConfig));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR SGBMConfig(::google::protobuf::internal::ConstantInitialized);

  inline SGBMConfig(const SGBMConfig& from) : SGBMConfig(nullptr, from) {}
  inline SGBMConfig(SGBMConfig&& from) noexcept
      : SGBMConfig(nullptr, std::move(from)) {}
  inline SGBMConfig& operator=(const SGBMConfig& from) {
    CopyFrom(from);
    return *this;
  }
  inline SGBMConfig& operator=(SGBMConfig&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SGBMConfig& default_instance() {
    return *reinterpret_cast<const SGBMConfig*>(
        &_SGBMConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(SGBMConfig& a, SGBMConfig& b) { a.Swap(&b); }
  inline void Swap(SGBMConfig* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SGBMConfig* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SGBMConfig* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<SGBMConfig>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SGBMConfig& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const SGBMConfig& from) { SGBMConfig::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(SGBMConfig* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "binocularpositioning.SGBMConfig"; }

 protected:
  explicit SGBMConfig(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  SGBMConfig(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const SGBMConfig& from);
  SGBMConfig(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, SGBMConfig&& from) noexcept
      : SGBMConfig(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kMinDisparityFieldNumber = 1,
    kNumDisparitiesFieldNumber = 2,
    kBlockSizeFieldNumber = 3,
    kP1FieldNumber = 4,
    kP2FieldNumber = 5,
    kDisp12MaxDiffFieldNumber = 6,
    kPreFilterCapFieldNumber = 7,
    kUniquenessRatioFieldNumber = 8,
    kSpeckleWindowSizeFieldNumber = 9,
    kSpeckleRangeFieldNumber = 10,
    kModeFieldNumber = 11,
  };
  // int32 min_disparity = 1;
  void clear_min_disparity() ;
  ::int32_t min_disparity() const;
  void set_min_disparity(::int32_t value);

  private:
  ::int32_t _internal_min_disparity() const;
  void _internal_set_min_disparity(::int32_t value);

  public:
  // int32 num_disparities = 2;
  void clear_num_disparities() ;
  ::int32_t num_disparities() const;
  void set_num_disparities(::int32_t value);

  private:
  ::int32_t _internal_num_disparities() const;
  void _internal_set_num_disparities(::int32_t value);

  public:
  // int32 block_size = 3;
  void clear_block_size() ;
  ::int32_t block_size() const;
  void set_block_size(::int32_t value);

  private:
  ::int32_t _internal_block_size() const;
  void _internal_set_block_size(::int32_t value);

  public:
  // int32 p1 = 4;
  void clear_p1() ;
  ::int32_t p1() const;
  void set_p1(::int32_t value);

  private:
  ::int32_t _internal_p1() const;
  void _internal_set_p1(::int32_t value);

  public:
  // int32 p2 = 5;
  void clear_p2() ;
  ::int32_t p2() const;
  void set_p2(::int32_t value);

  private:
  ::int32_t _internal_p2() const;
  void _internal_set_p2(::int32_t value);

  public:
  // int32 disp12_max_diff = 6;
  void clear_disp12_max_diff() ;
  ::int32_t disp12_max_diff() const;
  void set_disp12_max_diff(::int32_t value);

  private:
  ::int32_t _internal_disp12_max_diff() const;
  void _internal_set_disp12_max_diff(::int32_t value);

  public:
  // int32 pre_filter_cap = 7;
  void clear_pre_filter_cap() ;
  ::int32_t pre_filter_cap() const;
  void set_pre_filter_cap(::int32_t value);

  private:
  ::int32_t _internal_pre_filter_cap() const;
  void _internal_set_pre_filter_cap(::int32_t value);

  public:
  // int32 uniqueness_ratio = 8;
  void clear_uniqueness_ratio() ;
  ::int32_t uniqueness_ratio() const;
  void set_uniqueness_ratio(::int32_t value);

  private:
  ::int32_t _internal_uniqueness_ratio() const;
  void _internal_set_uniqueness_ratio(::int32_t value);

  public:
  // int32 speckle_window_size = 9;
  void clear_speckle_window_size() ;
  ::int32_t speckle_window_size() const;
  void set_speckle_window_size(::int32_t value);

  private:
  ::int32_t _internal_speckle_window_size() const;
  void _internal_set_speckle_window_size(::int32_t value);

  public:
  // int32 speckle_range = 10;
  void clear_speckle_range() ;
  ::int32_t speckle_range() const;
  void set_speckle_range(::int32_t value);

  private:
  ::int32_t _internal_speckle_range() const;
  void _internal_set_speckle_range(::int32_t value);

  public:
  // int32 mode = 11;
  void clear_mode() ;
  ::int32_t mode() const;
  void set_mode(::int32_t value);

  private:
  ::int32_t _internal_mode() const;
  void _internal_set_mode(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:binocularpositioning.SGBMConfig)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<4, 11,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const SGBMConfig& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::int32_t min_disparity_;
    ::int32_t num_disparities_;
    ::int32_t block_size_;
    ::int32_t p1_;
    ::int32_t p2_;
    ::int32_t disp12_max_diff_;
    ::int32_t pre_filter_cap_;
    ::int32_t uniqueness_ratio_;
    ::int32_t speckle_window_size_;
    ::int32_t speckle_range_;
    ::int32_t mode_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_BinocularPositioning_5fconf_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull SGBMConfig_class_data_;
// -------------------------------------------------------------------

class CRLConfig final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:binocularpositioning.CRLConfig) */ {
 public:
  inline CRLConfig() : CRLConfig(nullptr) {}
  ~CRLConfig() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(CRLConfig* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(CRLConfig));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR CRLConfig(::google::protobuf::internal::ConstantInitialized);

  inline CRLConfig(const CRLConfig& from) : CRLConfig(nullptr, from) {}
  inline CRLConfig(CRLConfig&& from) noexcept
      : CRLConfig(nullptr, std::move(from)) {}
  inline CRLConfig& operator=(const CRLConfig& from) {
    CopyFrom(from);
    return *this;
  }
  inline CRLConfig& operator=(CRLConfig&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CRLConfig& default_instance() {
    return *reinterpret_cast<const CRLConfig*>(
        &_CRLConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(CRLConfig& a, CRLConfig& b) { a.Swap(&b); }
  inline void Swap(CRLConfig* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CRLConfig* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CRLConfig* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<CRLConfig>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const CRLConfig& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const CRLConfig& from) { CRLConfig::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(CRLConfig* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "binocularpositioning.CRLConfig"; }

 protected:
  explicit CRLConfig(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  CRLConfig(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const CRLConfig& from);
  CRLConfig(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, CRLConfig&& from) noexcept
      : CRLConfig(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kEnginePathFieldNumber = 1,
  };
  // string engine_path = 1;
  void clear_engine_path() ;
  const std::string& engine_path() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_engine_path(Arg_&& arg, Args_... args);
  std::string* PROTOBUF_NONNULL mutable_engine_path();
  [[nodiscard]] std::string* PROTOBUF_NULLABLE release_engine_path();
  void set_allocated_engine_path(std::string* PROTOBUF_NULLABLE value);

  private:
  const std::string& _internal_engine_path() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_engine_path(const std::string& value);
  std::string* PROTOBUF_NONNULL _internal_mutable_engine_path();

  public:
  // @@protoc_insertion_point(class_scope:binocularpositioning.CRLConfig)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 50,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const CRLConfig& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr engine_path_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_BinocularPositioning_5fconf_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull CRLConfig_class_data_;
// -------------------------------------------------------------------

class ModelConfig final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:binocularpositioning.ModelConfig) */ {
 public:
  inline ModelConfig() : ModelConfig(nullptr) {}
  ~ModelConfig() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ModelConfig* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ModelConfig));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ModelConfig(::google::protobuf::internal::ConstantInitialized);

  inline ModelConfig(const ModelConfig& from) : ModelConfig(nullptr, from) {}
  inline ModelConfig(ModelConfig&& from) noexcept
      : ModelConfig(nullptr, std::move(from)) {}
  inline ModelConfig& operator=(const ModelConfig& from) {
    CopyFrom(from);
    return *this;
  }
  inline ModelConfig& operator=(ModelConfig&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ModelConfig& default_instance() {
    return *reinterpret_cast<const ModelConfig*>(
        &_ModelConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(ModelConfig& a, ModelConfig& b) { a.Swap(&b); }
  inline void Swap(ModelConfig* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ModelConfig* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ModelConfig* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ModelConfig>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ModelConfig& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ModelConfig& from) { ModelConfig::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ModelConfig* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "binocularpositioning.ModelConfig"; }

 protected:
  explicit ModelConfig(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  ModelConfig(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const ModelConfig& from);
  ModelConfig(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, ModelConfig&& from) noexcept
      : ModelConfig(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kSgbmConfigFieldNumber = 1,
    kCrlConfigFieldNumber = 2,
    kRunStatusFieldNumber = 3,
    kBaselineFieldNumber = 4,
    kFocusPixelFieldNumber = 5,
    kFocalLengthFieldNumber = 6,
  };
  // .binocularpositioning.SGBMConfig sgbm_config = 1;
  bool has_sgbm_config() const;
  void clear_sgbm_config() ;
  const ::binocularpositioning::SGBMConfig& sgbm_config() const;
  [[nodiscard]] ::binocularpositioning::SGBMConfig* PROTOBUF_NULLABLE release_sgbm_config();
  ::binocularpositioning::SGBMConfig* PROTOBUF_NONNULL mutable_sgbm_config();
  void set_allocated_sgbm_config(::binocularpositioning::SGBMConfig* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_sgbm_config(::binocularpositioning::SGBMConfig* PROTOBUF_NULLABLE value);
  ::binocularpositioning::SGBMConfig* PROTOBUF_NULLABLE unsafe_arena_release_sgbm_config();

  private:
  const ::binocularpositioning::SGBMConfig& _internal_sgbm_config() const;
  ::binocularpositioning::SGBMConfig* PROTOBUF_NONNULL _internal_mutable_sgbm_config();

  public:
  // .binocularpositioning.CRLConfig crl_config = 2;
  bool has_crl_config() const;
  void clear_crl_config() ;
  const ::binocularpositioning::CRLConfig& crl_config() const;
  [[nodiscard]] ::binocularpositioning::CRLConfig* PROTOBUF_NULLABLE release_crl_config();
  ::binocularpositioning::CRLConfig* PROTOBUF_NONNULL mutable_crl_config();
  void set_allocated_crl_config(::binocularpositioning::CRLConfig* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_crl_config(::binocularpositioning::CRLConfig* PROTOBUF_NULLABLE value);
  ::binocularpositioning::CRLConfig* PROTOBUF_NULLABLE unsafe_arena_release_crl_config();

  private:
  const ::binocularpositioning::CRLConfig& _internal_crl_config() const;
  ::binocularpositioning::CRLConfig* PROTOBUF_NONNULL _internal_mutable_crl_config();

  public:
  // bool run_status = 3;
  void clear_run_status() ;
  bool run_status() const;
  void set_run_status(bool value);

  private:
  bool _internal_run_status() const;
  void _internal_set_run_status(bool value);

  public:
  // float baseline = 4;
  void clear_baseline() ;
  float baseline() const;
  void set_baseline(float value);

  private:
  float _internal_baseline() const;
  void _internal_set_baseline(float value);

  public:
  // int32 focus_pixel = 5;
  void clear_focus_pixel() ;
  ::int32_t focus_pixel() const;
  void set_focus_pixel(::int32_t value);

  private:
  ::int32_t _internal_focus_pixel() const;
  void _internal_set_focus_pixel(::int32_t value);

  public:
  // float focal_length = 6;
  void clear_focal_length() ;
  float focal_length() const;
  void set_focal_length(float value);

  private:
  float _internal_focal_length() const;
  void _internal_set_focal_length(float value);

  public:
  // @@protoc_insertion_point(class_scope:binocularpositioning.ModelConfig)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 6,
                                   2, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const ModelConfig& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::binocularpositioning::SGBMConfig* PROTOBUF_NULLABLE sgbm_config_;
    ::binocularpositioning::CRLConfig* PROTOBUF_NULLABLE crl_config_;
    bool run_status_;
    float baseline_;
    ::int32_t focus_pixel_;
    float focal_length_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_BinocularPositioning_5fconf_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull ModelConfig_class_data_;
// -------------------------------------------------------------------

class BinocularPositioningConfig final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:binocularpositioning.BinocularPositioningConfig) */ {
 public:
  inline BinocularPositioningConfig() : BinocularPositioningConfig(nullptr) {}
  ~BinocularPositioningConfig() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(BinocularPositioningConfig* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(BinocularPositioningConfig));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR BinocularPositioningConfig(::google::protobuf::internal::ConstantInitialized);

  inline BinocularPositioningConfig(const BinocularPositioningConfig& from) : BinocularPositioningConfig(nullptr, from) {}
  inline BinocularPositioningConfig(BinocularPositioningConfig&& from) noexcept
      : BinocularPositioningConfig(nullptr, std::move(from)) {}
  inline BinocularPositioningConfig& operator=(const BinocularPositioningConfig& from) {
    CopyFrom(from);
    return *this;
  }
  inline BinocularPositioningConfig& operator=(BinocularPositioningConfig&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BinocularPositioningConfig& default_instance() {
    return *reinterpret_cast<const BinocularPositioningConfig*>(
        &_BinocularPositioningConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(BinocularPositioningConfig& a, BinocularPositioningConfig& b) { a.Swap(&b); }
  inline void Swap(BinocularPositioningConfig* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BinocularPositioningConfig* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BinocularPositioningConfig* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<BinocularPositioningConfig>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const BinocularPositioningConfig& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const BinocularPositioningConfig& from) { BinocularPositioningConfig::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(BinocularPositioningConfig* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "binocularpositioning.BinocularPositioningConfig"; }

 protected:
  explicit BinocularPositioningConfig(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  BinocularPositioningConfig(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const BinocularPositioningConfig& from);
  BinocularPositioningConfig(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, BinocularPositioningConfig&& from) noexcept
      : BinocularPositioningConfig(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kModelConfigFieldNumber = 1,
    kModulesConfigFieldNumber = 2,
  };
  // .binocularpositioning.ModelConfig model_config = 1;
  bool has_model_config() const;
  void clear_model_config() ;
  const ::binocularpositioning::ModelConfig& model_config() const;
  [[nodiscard]] ::binocularpositioning::ModelConfig* PROTOBUF_NULLABLE release_model_config();
  ::binocularpositioning::ModelConfig* PROTOBUF_NONNULL mutable_model_config();
  void set_allocated_model_config(::binocularpositioning::ModelConfig* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_model_config(::binocularpositioning::ModelConfig* PROTOBUF_NULLABLE value);
  ::binocularpositioning::ModelConfig* PROTOBUF_NULLABLE unsafe_arena_release_model_config();

  private:
  const ::binocularpositioning::ModelConfig& _internal_model_config() const;
  ::binocularpositioning::ModelConfig* PROTOBUF_NONNULL _internal_mutable_model_config();

  public:
  // .common.ModulesConfig modules_config = 2;
  bool has_modules_config() const;
  void clear_modules_config() ;
  const ::common::ModulesConfig& modules_config() const;
  [[nodiscard]] ::common::ModulesConfig* PROTOBUF_NULLABLE release_modules_config();
  ::common::ModulesConfig* PROTOBUF_NONNULL mutable_modules_config();
  void set_allocated_modules_config(::common::ModulesConfig* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_modules_config(::common::ModulesConfig* PROTOBUF_NULLABLE value);
  ::common::ModulesConfig* PROTOBUF_NULLABLE unsafe_arena_release_modules_config();

  private:
  const ::common::ModulesConfig& _internal_modules_config() const;
  ::common::ModulesConfig* PROTOBUF_NONNULL _internal_mutable_modules_config();

  public:
  // @@protoc_insertion_point(class_scope:binocularpositioning.BinocularPositioningConfig)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   2, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const BinocularPositioningConfig& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::binocularpositioning::ModelConfig* PROTOBUF_NULLABLE model_config_;
    ::common::ModulesConfig* PROTOBUF_NULLABLE modules_config_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_BinocularPositioning_5fconf_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull BinocularPositioningConfig_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// SGBMConfig

// int32 min_disparity = 1;
inline void SGBMConfig::clear_min_disparity() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.min_disparity_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::int32_t SGBMConfig::min_disparity() const {
  // @@protoc_insertion_point(field_get:binocularpositioning.SGBMConfig.min_disparity)
  return _internal_min_disparity();
}
inline void SGBMConfig::set_min_disparity(::int32_t value) {
  _internal_set_min_disparity(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:binocularpositioning.SGBMConfig.min_disparity)
}
inline ::int32_t SGBMConfig::_internal_min_disparity() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.min_disparity_;
}
inline void SGBMConfig::_internal_set_min_disparity(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.min_disparity_ = value;
}

// int32 num_disparities = 2;
inline void SGBMConfig::clear_num_disparities() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.num_disparities_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline ::int32_t SGBMConfig::num_disparities() const {
  // @@protoc_insertion_point(field_get:binocularpositioning.SGBMConfig.num_disparities)
  return _internal_num_disparities();
}
inline void SGBMConfig::set_num_disparities(::int32_t value) {
  _internal_set_num_disparities(value);
  _impl_._has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_set:binocularpositioning.SGBMConfig.num_disparities)
}
inline ::int32_t SGBMConfig::_internal_num_disparities() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.num_disparities_;
}
inline void SGBMConfig::_internal_set_num_disparities(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.num_disparities_ = value;
}

// int32 block_size = 3;
inline void SGBMConfig::clear_block_size() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.block_size_ = 0;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline ::int32_t SGBMConfig::block_size() const {
  // @@protoc_insertion_point(field_get:binocularpositioning.SGBMConfig.block_size)
  return _internal_block_size();
}
inline void SGBMConfig::set_block_size(::int32_t value) {
  _internal_set_block_size(value);
  _impl_._has_bits_[0] |= 0x00000004u;
  // @@protoc_insertion_point(field_set:binocularpositioning.SGBMConfig.block_size)
}
inline ::int32_t SGBMConfig::_internal_block_size() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.block_size_;
}
inline void SGBMConfig::_internal_set_block_size(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.block_size_ = value;
}

// int32 p1 = 4;
inline void SGBMConfig::clear_p1() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.p1_ = 0;
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline ::int32_t SGBMConfig::p1() const {
  // @@protoc_insertion_point(field_get:binocularpositioning.SGBMConfig.p1)
  return _internal_p1();
}
inline void SGBMConfig::set_p1(::int32_t value) {
  _internal_set_p1(value);
  _impl_._has_bits_[0] |= 0x00000008u;
  // @@protoc_insertion_point(field_set:binocularpositioning.SGBMConfig.p1)
}
inline ::int32_t SGBMConfig::_internal_p1() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.p1_;
}
inline void SGBMConfig::_internal_set_p1(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.p1_ = value;
}

// int32 p2 = 5;
inline void SGBMConfig::clear_p2() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.p2_ = 0;
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline ::int32_t SGBMConfig::p2() const {
  // @@protoc_insertion_point(field_get:binocularpositioning.SGBMConfig.p2)
  return _internal_p2();
}
inline void SGBMConfig::set_p2(::int32_t value) {
  _internal_set_p2(value);
  _impl_._has_bits_[0] |= 0x00000010u;
  // @@protoc_insertion_point(field_set:binocularpositioning.SGBMConfig.p2)
}
inline ::int32_t SGBMConfig::_internal_p2() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.p2_;
}
inline void SGBMConfig::_internal_set_p2(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.p2_ = value;
}

// int32 disp12_max_diff = 6;
inline void SGBMConfig::clear_disp12_max_diff() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.disp12_max_diff_ = 0;
  _impl_._has_bits_[0] &= ~0x00000020u;
}
inline ::int32_t SGBMConfig::disp12_max_diff() const {
  // @@protoc_insertion_point(field_get:binocularpositioning.SGBMConfig.disp12_max_diff)
  return _internal_disp12_max_diff();
}
inline void SGBMConfig::set_disp12_max_diff(::int32_t value) {
  _internal_set_disp12_max_diff(value);
  _impl_._has_bits_[0] |= 0x00000020u;
  // @@protoc_insertion_point(field_set:binocularpositioning.SGBMConfig.disp12_max_diff)
}
inline ::int32_t SGBMConfig::_internal_disp12_max_diff() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.disp12_max_diff_;
}
inline void SGBMConfig::_internal_set_disp12_max_diff(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.disp12_max_diff_ = value;
}

// int32 pre_filter_cap = 7;
inline void SGBMConfig::clear_pre_filter_cap() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pre_filter_cap_ = 0;
  _impl_._has_bits_[0] &= ~0x00000040u;
}
inline ::int32_t SGBMConfig::pre_filter_cap() const {
  // @@protoc_insertion_point(field_get:binocularpositioning.SGBMConfig.pre_filter_cap)
  return _internal_pre_filter_cap();
}
inline void SGBMConfig::set_pre_filter_cap(::int32_t value) {
  _internal_set_pre_filter_cap(value);
  _impl_._has_bits_[0] |= 0x00000040u;
  // @@protoc_insertion_point(field_set:binocularpositioning.SGBMConfig.pre_filter_cap)
}
inline ::int32_t SGBMConfig::_internal_pre_filter_cap() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pre_filter_cap_;
}
inline void SGBMConfig::_internal_set_pre_filter_cap(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pre_filter_cap_ = value;
}

// int32 uniqueness_ratio = 8;
inline void SGBMConfig::clear_uniqueness_ratio() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.uniqueness_ratio_ = 0;
  _impl_._has_bits_[0] &= ~0x00000080u;
}
inline ::int32_t SGBMConfig::uniqueness_ratio() const {
  // @@protoc_insertion_point(field_get:binocularpositioning.SGBMConfig.uniqueness_ratio)
  return _internal_uniqueness_ratio();
}
inline void SGBMConfig::set_uniqueness_ratio(::int32_t value) {
  _internal_set_uniqueness_ratio(value);
  _impl_._has_bits_[0] |= 0x00000080u;
  // @@protoc_insertion_point(field_set:binocularpositioning.SGBMConfig.uniqueness_ratio)
}
inline ::int32_t SGBMConfig::_internal_uniqueness_ratio() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.uniqueness_ratio_;
}
inline void SGBMConfig::_internal_set_uniqueness_ratio(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.uniqueness_ratio_ = value;
}

// int32 speckle_window_size = 9;
inline void SGBMConfig::clear_speckle_window_size() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.speckle_window_size_ = 0;
  _impl_._has_bits_[0] &= ~0x00000100u;
}
inline ::int32_t SGBMConfig::speckle_window_size() const {
  // @@protoc_insertion_point(field_get:binocularpositioning.SGBMConfig.speckle_window_size)
  return _internal_speckle_window_size();
}
inline void SGBMConfig::set_speckle_window_size(::int32_t value) {
  _internal_set_speckle_window_size(value);
  _impl_._has_bits_[0] |= 0x00000100u;
  // @@protoc_insertion_point(field_set:binocularpositioning.SGBMConfig.speckle_window_size)
}
inline ::int32_t SGBMConfig::_internal_speckle_window_size() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.speckle_window_size_;
}
inline void SGBMConfig::_internal_set_speckle_window_size(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.speckle_window_size_ = value;
}

// int32 speckle_range = 10;
inline void SGBMConfig::clear_speckle_range() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.speckle_range_ = 0;
  _impl_._has_bits_[0] &= ~0x00000200u;
}
inline ::int32_t SGBMConfig::speckle_range() const {
  // @@protoc_insertion_point(field_get:binocularpositioning.SGBMConfig.speckle_range)
  return _internal_speckle_range();
}
inline void SGBMConfig::set_speckle_range(::int32_t value) {
  _internal_set_speckle_range(value);
  _impl_._has_bits_[0] |= 0x00000200u;
  // @@protoc_insertion_point(field_set:binocularpositioning.SGBMConfig.speckle_range)
}
inline ::int32_t SGBMConfig::_internal_speckle_range() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.speckle_range_;
}
inline void SGBMConfig::_internal_set_speckle_range(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.speckle_range_ = value;
}

// int32 mode = 11;
inline void SGBMConfig::clear_mode() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.mode_ = 0;
  _impl_._has_bits_[0] &= ~0x00000400u;
}
inline ::int32_t SGBMConfig::mode() const {
  // @@protoc_insertion_point(field_get:binocularpositioning.SGBMConfig.mode)
  return _internal_mode();
}
inline void SGBMConfig::set_mode(::int32_t value) {
  _internal_set_mode(value);
  _impl_._has_bits_[0] |= 0x00000400u;
  // @@protoc_insertion_point(field_set:binocularpositioning.SGBMConfig.mode)
}
inline ::int32_t SGBMConfig::_internal_mode() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.mode_;
}
inline void SGBMConfig::_internal_set_mode(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.mode_ = value;
}

// -------------------------------------------------------------------

// CRLConfig

// string engine_path = 1;
inline void CRLConfig::clear_engine_path() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.engine_path_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& CRLConfig::engine_path() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:binocularpositioning.CRLConfig.engine_path)
  return _internal_engine_path();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void CRLConfig::set_engine_path(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.engine_path_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:binocularpositioning.CRLConfig.engine_path)
}
inline std::string* PROTOBUF_NONNULL CRLConfig::mutable_engine_path()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_engine_path();
  // @@protoc_insertion_point(field_mutable:binocularpositioning.CRLConfig.engine_path)
  return _s;
}
inline const std::string& CRLConfig::_internal_engine_path() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.engine_path_.Get();
}
inline void CRLConfig::_internal_set_engine_path(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.engine_path_.Set(value, GetArena());
}
inline std::string* PROTOBUF_NONNULL CRLConfig::_internal_mutable_engine_path() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.engine_path_.Mutable( GetArena());
}
inline std::string* PROTOBUF_NULLABLE CRLConfig::release_engine_path() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:binocularpositioning.CRLConfig.engine_path)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.engine_path_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.engine_path_.Set("", GetArena());
  }
  return released;
}
inline void CRLConfig::set_allocated_engine_path(std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.engine_path_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.engine_path_.IsDefault()) {
    _impl_.engine_path_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:binocularpositioning.CRLConfig.engine_path)
}

// -------------------------------------------------------------------

// ModelConfig

// .binocularpositioning.SGBMConfig sgbm_config = 1;
inline bool ModelConfig::has_sgbm_config() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.sgbm_config_ != nullptr);
  return value;
}
inline void ModelConfig::clear_sgbm_config() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.sgbm_config_ != nullptr) _impl_.sgbm_config_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::binocularpositioning::SGBMConfig& ModelConfig::_internal_sgbm_config() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::binocularpositioning::SGBMConfig* p = _impl_.sgbm_config_;
  return p != nullptr ? *p : reinterpret_cast<const ::binocularpositioning::SGBMConfig&>(::binocularpositioning::_SGBMConfig_default_instance_);
}
inline const ::binocularpositioning::SGBMConfig& ModelConfig::sgbm_config() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:binocularpositioning.ModelConfig.sgbm_config)
  return _internal_sgbm_config();
}
inline void ModelConfig::unsafe_arena_set_allocated_sgbm_config(
    ::binocularpositioning::SGBMConfig* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.sgbm_config_);
  }
  _impl_.sgbm_config_ = reinterpret_cast<::binocularpositioning::SGBMConfig*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:binocularpositioning.ModelConfig.sgbm_config)
}
inline ::binocularpositioning::SGBMConfig* PROTOBUF_NULLABLE ModelConfig::release_sgbm_config() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::binocularpositioning::SGBMConfig* released = _impl_.sgbm_config_;
  _impl_.sgbm_config_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::binocularpositioning::SGBMConfig* PROTOBUF_NULLABLE ModelConfig::unsafe_arena_release_sgbm_config() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:binocularpositioning.ModelConfig.sgbm_config)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::binocularpositioning::SGBMConfig* temp = _impl_.sgbm_config_;
  _impl_.sgbm_config_ = nullptr;
  return temp;
}
inline ::binocularpositioning::SGBMConfig* PROTOBUF_NONNULL ModelConfig::_internal_mutable_sgbm_config() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.sgbm_config_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::binocularpositioning::SGBMConfig>(GetArena());
    _impl_.sgbm_config_ = reinterpret_cast<::binocularpositioning::SGBMConfig*>(p);
  }
  return _impl_.sgbm_config_;
}
inline ::binocularpositioning::SGBMConfig* PROTOBUF_NONNULL ModelConfig::mutable_sgbm_config()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::binocularpositioning::SGBMConfig* _msg = _internal_mutable_sgbm_config();
  // @@protoc_insertion_point(field_mutable:binocularpositioning.ModelConfig.sgbm_config)
  return _msg;
}
inline void ModelConfig::set_allocated_sgbm_config(::binocularpositioning::SGBMConfig* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.sgbm_config_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = value->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.sgbm_config_ = reinterpret_cast<::binocularpositioning::SGBMConfig*>(value);
  // @@protoc_insertion_point(field_set_allocated:binocularpositioning.ModelConfig.sgbm_config)
}

// .binocularpositioning.CRLConfig crl_config = 2;
inline bool ModelConfig::has_crl_config() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.crl_config_ != nullptr);
  return value;
}
inline void ModelConfig::clear_crl_config() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.crl_config_ != nullptr) _impl_.crl_config_->Clear();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const ::binocularpositioning::CRLConfig& ModelConfig::_internal_crl_config() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::binocularpositioning::CRLConfig* p = _impl_.crl_config_;
  return p != nullptr ? *p : reinterpret_cast<const ::binocularpositioning::CRLConfig&>(::binocularpositioning::_CRLConfig_default_instance_);
}
inline const ::binocularpositioning::CRLConfig& ModelConfig::crl_config() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:binocularpositioning.ModelConfig.crl_config)
  return _internal_crl_config();
}
inline void ModelConfig::unsafe_arena_set_allocated_crl_config(
    ::binocularpositioning::CRLConfig* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.crl_config_);
  }
  _impl_.crl_config_ = reinterpret_cast<::binocularpositioning::CRLConfig*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:binocularpositioning.ModelConfig.crl_config)
}
inline ::binocularpositioning::CRLConfig* PROTOBUF_NULLABLE ModelConfig::release_crl_config() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::binocularpositioning::CRLConfig* released = _impl_.crl_config_;
  _impl_.crl_config_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::binocularpositioning::CRLConfig* PROTOBUF_NULLABLE ModelConfig::unsafe_arena_release_crl_config() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:binocularpositioning.ModelConfig.crl_config)

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::binocularpositioning::CRLConfig* temp = _impl_.crl_config_;
  _impl_.crl_config_ = nullptr;
  return temp;
}
inline ::binocularpositioning::CRLConfig* PROTOBUF_NONNULL ModelConfig::_internal_mutable_crl_config() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.crl_config_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::binocularpositioning::CRLConfig>(GetArena());
    _impl_.crl_config_ = reinterpret_cast<::binocularpositioning::CRLConfig*>(p);
  }
  return _impl_.crl_config_;
}
inline ::binocularpositioning::CRLConfig* PROTOBUF_NONNULL ModelConfig::mutable_crl_config()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000002u;
  ::binocularpositioning::CRLConfig* _msg = _internal_mutable_crl_config();
  // @@protoc_insertion_point(field_mutable:binocularpositioning.ModelConfig.crl_config)
  return _msg;
}
inline void ModelConfig::set_allocated_crl_config(::binocularpositioning::CRLConfig* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.crl_config_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = value->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }

  _impl_.crl_config_ = reinterpret_cast<::binocularpositioning::CRLConfig*>(value);
  // @@protoc_insertion_point(field_set_allocated:binocularpositioning.ModelConfig.crl_config)
}

// bool run_status = 3;
inline void ModelConfig::clear_run_status() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.run_status_ = false;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline bool ModelConfig::run_status() const {
  // @@protoc_insertion_point(field_get:binocularpositioning.ModelConfig.run_status)
  return _internal_run_status();
}
inline void ModelConfig::set_run_status(bool value) {
  _internal_set_run_status(value);
  _impl_._has_bits_[0] |= 0x00000004u;
  // @@protoc_insertion_point(field_set:binocularpositioning.ModelConfig.run_status)
}
inline bool ModelConfig::_internal_run_status() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.run_status_;
}
inline void ModelConfig::_internal_set_run_status(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.run_status_ = value;
}

// float baseline = 4;
inline void ModelConfig::clear_baseline() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.baseline_ = 0;
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline float ModelConfig::baseline() const {
  // @@protoc_insertion_point(field_get:binocularpositioning.ModelConfig.baseline)
  return _internal_baseline();
}
inline void ModelConfig::set_baseline(float value) {
  _internal_set_baseline(value);
  _impl_._has_bits_[0] |= 0x00000008u;
  // @@protoc_insertion_point(field_set:binocularpositioning.ModelConfig.baseline)
}
inline float ModelConfig::_internal_baseline() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.baseline_;
}
inline void ModelConfig::_internal_set_baseline(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.baseline_ = value;
}

// int32 focus_pixel = 5;
inline void ModelConfig::clear_focus_pixel() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.focus_pixel_ = 0;
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline ::int32_t ModelConfig::focus_pixel() const {
  // @@protoc_insertion_point(field_get:binocularpositioning.ModelConfig.focus_pixel)
  return _internal_focus_pixel();
}
inline void ModelConfig::set_focus_pixel(::int32_t value) {
  _internal_set_focus_pixel(value);
  _impl_._has_bits_[0] |= 0x00000010u;
  // @@protoc_insertion_point(field_set:binocularpositioning.ModelConfig.focus_pixel)
}
inline ::int32_t ModelConfig::_internal_focus_pixel() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.focus_pixel_;
}
inline void ModelConfig::_internal_set_focus_pixel(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.focus_pixel_ = value;
}

// float focal_length = 6;
inline void ModelConfig::clear_focal_length() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.focal_length_ = 0;
  _impl_._has_bits_[0] &= ~0x00000020u;
}
inline float ModelConfig::focal_length() const {
  // @@protoc_insertion_point(field_get:binocularpositioning.ModelConfig.focal_length)
  return _internal_focal_length();
}
inline void ModelConfig::set_focal_length(float value) {
  _internal_set_focal_length(value);
  _impl_._has_bits_[0] |= 0x00000020u;
  // @@protoc_insertion_point(field_set:binocularpositioning.ModelConfig.focal_length)
}
inline float ModelConfig::_internal_focal_length() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.focal_length_;
}
inline void ModelConfig::_internal_set_focal_length(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.focal_length_ = value;
}

// -------------------------------------------------------------------

// BinocularPositioningConfig

// .binocularpositioning.ModelConfig model_config = 1;
inline bool BinocularPositioningConfig::has_model_config() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.model_config_ != nullptr);
  return value;
}
inline void BinocularPositioningConfig::clear_model_config() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.model_config_ != nullptr) _impl_.model_config_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::binocularpositioning::ModelConfig& BinocularPositioningConfig::_internal_model_config() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::binocularpositioning::ModelConfig* p = _impl_.model_config_;
  return p != nullptr ? *p : reinterpret_cast<const ::binocularpositioning::ModelConfig&>(::binocularpositioning::_ModelConfig_default_instance_);
}
inline const ::binocularpositioning::ModelConfig& BinocularPositioningConfig::model_config() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:binocularpositioning.BinocularPositioningConfig.model_config)
  return _internal_model_config();
}
inline void BinocularPositioningConfig::unsafe_arena_set_allocated_model_config(
    ::binocularpositioning::ModelConfig* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.model_config_);
  }
  _impl_.model_config_ = reinterpret_cast<::binocularpositioning::ModelConfig*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:binocularpositioning.BinocularPositioningConfig.model_config)
}
inline ::binocularpositioning::ModelConfig* PROTOBUF_NULLABLE BinocularPositioningConfig::release_model_config() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::binocularpositioning::ModelConfig* released = _impl_.model_config_;
  _impl_.model_config_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::binocularpositioning::ModelConfig* PROTOBUF_NULLABLE BinocularPositioningConfig::unsafe_arena_release_model_config() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:binocularpositioning.BinocularPositioningConfig.model_config)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::binocularpositioning::ModelConfig* temp = _impl_.model_config_;
  _impl_.model_config_ = nullptr;
  return temp;
}
inline ::binocularpositioning::ModelConfig* PROTOBUF_NONNULL BinocularPositioningConfig::_internal_mutable_model_config() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.model_config_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::binocularpositioning::ModelConfig>(GetArena());
    _impl_.model_config_ = reinterpret_cast<::binocularpositioning::ModelConfig*>(p);
  }
  return _impl_.model_config_;
}
inline ::binocularpositioning::ModelConfig* PROTOBUF_NONNULL BinocularPositioningConfig::mutable_model_config()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::binocularpositioning::ModelConfig* _msg = _internal_mutable_model_config();
  // @@protoc_insertion_point(field_mutable:binocularpositioning.BinocularPositioningConfig.model_config)
  return _msg;
}
inline void BinocularPositioningConfig::set_allocated_model_config(::binocularpositioning::ModelConfig* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.model_config_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = value->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.model_config_ = reinterpret_cast<::binocularpositioning::ModelConfig*>(value);
  // @@protoc_insertion_point(field_set_allocated:binocularpositioning.BinocularPositioningConfig.model_config)
}

// .common.ModulesConfig modules_config = 2;
inline bool BinocularPositioningConfig::has_modules_config() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.modules_config_ != nullptr);
  return value;
}
inline const ::common::ModulesConfig& BinocularPositioningConfig::_internal_modules_config() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::common::ModulesConfig* p = _impl_.modules_config_;
  return p != nullptr ? *p : reinterpret_cast<const ::common::ModulesConfig&>(::common::_ModulesConfig_default_instance_);
}
inline const ::common::ModulesConfig& BinocularPositioningConfig::modules_config() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:binocularpositioning.BinocularPositioningConfig.modules_config)
  return _internal_modules_config();
}
inline void BinocularPositioningConfig::unsafe_arena_set_allocated_modules_config(
    ::common::ModulesConfig* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.modules_config_);
  }
  _impl_.modules_config_ = reinterpret_cast<::common::ModulesConfig*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:binocularpositioning.BinocularPositioningConfig.modules_config)
}
inline ::common::ModulesConfig* PROTOBUF_NULLABLE BinocularPositioningConfig::release_modules_config() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::common::ModulesConfig* released = _impl_.modules_config_;
  _impl_.modules_config_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::common::ModulesConfig* PROTOBUF_NULLABLE BinocularPositioningConfig::unsafe_arena_release_modules_config() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:binocularpositioning.BinocularPositioningConfig.modules_config)

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::common::ModulesConfig* temp = _impl_.modules_config_;
  _impl_.modules_config_ = nullptr;
  return temp;
}
inline ::common::ModulesConfig* PROTOBUF_NONNULL BinocularPositioningConfig::_internal_mutable_modules_config() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.modules_config_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::common::ModulesConfig>(GetArena());
    _impl_.modules_config_ = reinterpret_cast<::common::ModulesConfig*>(p);
  }
  return _impl_.modules_config_;
}
inline ::common::ModulesConfig* PROTOBUF_NONNULL BinocularPositioningConfig::mutable_modules_config()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000002u;
  ::common::ModulesConfig* _msg = _internal_mutable_modules_config();
  // @@protoc_insertion_point(field_mutable:binocularpositioning.BinocularPositioningConfig.modules_config)
  return _msg;
}
inline void BinocularPositioningConfig::set_allocated_modules_config(::common::ModulesConfig* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.modules_config_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }

  _impl_.modules_config_ = reinterpret_cast<::common::ModulesConfig*>(value);
  // @@protoc_insertion_point(field_set_allocated:binocularpositioning.BinocularPositioningConfig.modules_config)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace binocularpositioning


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // BinocularPositioning_5fconf_2eproto_2epb_2eh
