// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: MultiModalFusion_conf.proto
// Protobuf C++ Version: 5.30.0-dev

#include "MultiModalFusion_conf.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr MultiModalFusionModelConfig::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        stride_{},
        _stride_cached_byte_size_{0},
        engine_path_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        num_class_{0},
        batch_size_{0},
        width_{0},
        height_{0},
        conf_thres_{0},
        iou_thres_{0},
        src_width_{0},
        src_height_{0},
        resize_ratio_{0},
        dw_{0},
        dh_{0},
        new_unpad_w_{0},
        new_unpad_h_{0},
        max_dets_{0},
        channels_{0},
        run_status_{false} {}

template <typename>
PROTOBUF_CONSTEXPR MultiModalFusionModelConfig::MultiModalFusionModelConfig(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(MultiModalFusionModelConfig_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct MultiModalFusionModelConfigDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MultiModalFusionModelConfigDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MultiModalFusionModelConfigDefaultTypeInternal() {}
  union {
    MultiModalFusionModelConfig _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MultiModalFusionModelConfigDefaultTypeInternal _MultiModalFusionModelConfig_default_instance_;

inline constexpr ModuleConfig::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        type_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR ModuleConfig::ModuleConfig(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(ModuleConfig_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ModuleConfigDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ModuleConfigDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ModuleConfigDefaultTypeInternal() {}
  union {
    ModuleConfig _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ModuleConfigDefaultTypeInternal _ModuleConfig_default_instance_;

inline constexpr ModulesConfig::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : modules_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ModulesConfig::ModulesConfig(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(ModulesConfig_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ModulesConfigDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ModulesConfigDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ModulesConfigDefaultTypeInternal() {}
  union {
    ModulesConfig _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ModulesConfigDefaultTypeInternal _ModulesConfig_default_instance_;

inline constexpr MultiModalFusionConfig::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        model_config_{nullptr},
        modules_config_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR MultiModalFusionConfig::MultiModalFusionConfig(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(MultiModalFusionConfig_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct MultiModalFusionConfigDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MultiModalFusionConfigDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MultiModalFusionConfigDefaultTypeInternal() {}
  union {
    MultiModalFusionConfig _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MultiModalFusionConfigDefaultTypeInternal _MultiModalFusionConfig_default_instance_;
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_MultiModalFusion_5fconf_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_MultiModalFusion_5fconf_2eproto = nullptr;
const ::uint32_t
    TableStruct_MultiModalFusion_5fconf_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::ModuleConfig, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::ModuleConfig, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::ModuleConfig, _impl_.type_),
        PROTOBUF_FIELD_OFFSET(::ModuleConfig, _impl_.name_),
        0,
        1,
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::ModulesConfig, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::ModulesConfig, _impl_.modules_),
        PROTOBUF_FIELD_OFFSET(::MultiModalFusionModelConfig, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::MultiModalFusionModelConfig, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::MultiModalFusionModelConfig, _impl_.engine_path_),
        PROTOBUF_FIELD_OFFSET(::MultiModalFusionModelConfig, _impl_.num_class_),
        PROTOBUF_FIELD_OFFSET(::MultiModalFusionModelConfig, _impl_.batch_size_),
        PROTOBUF_FIELD_OFFSET(::MultiModalFusionModelConfig, _impl_.width_),
        PROTOBUF_FIELD_OFFSET(::MultiModalFusionModelConfig, _impl_.height_),
        PROTOBUF_FIELD_OFFSET(::MultiModalFusionModelConfig, _impl_.conf_thres_),
        PROTOBUF_FIELD_OFFSET(::MultiModalFusionModelConfig, _impl_.iou_thres_),
        PROTOBUF_FIELD_OFFSET(::MultiModalFusionModelConfig, _impl_.stride_),
        PROTOBUF_FIELD_OFFSET(::MultiModalFusionModelConfig, _impl_.src_width_),
        PROTOBUF_FIELD_OFFSET(::MultiModalFusionModelConfig, _impl_.src_height_),
        PROTOBUF_FIELD_OFFSET(::MultiModalFusionModelConfig, _impl_.resize_ratio_),
        PROTOBUF_FIELD_OFFSET(::MultiModalFusionModelConfig, _impl_.dw_),
        PROTOBUF_FIELD_OFFSET(::MultiModalFusionModelConfig, _impl_.dh_),
        PROTOBUF_FIELD_OFFSET(::MultiModalFusionModelConfig, _impl_.new_unpad_w_),
        PROTOBUF_FIELD_OFFSET(::MultiModalFusionModelConfig, _impl_.new_unpad_h_),
        PROTOBUF_FIELD_OFFSET(::MultiModalFusionModelConfig, _impl_.max_dets_),
        PROTOBUF_FIELD_OFFSET(::MultiModalFusionModelConfig, _impl_.channels_),
        PROTOBUF_FIELD_OFFSET(::MultiModalFusionModelConfig, _impl_.run_status_),
        0,
        1,
        2,
        3,
        4,
        5,
        6,
        ~0u,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        14,
        15,
        16,
        PROTOBUF_FIELD_OFFSET(::MultiModalFusionConfig, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::MultiModalFusionConfig, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::MultiModalFusionConfig, _impl_.model_config_),
        PROTOBUF_FIELD_OFFSET(::MultiModalFusionConfig, _impl_.modules_config_),
        0,
        1,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 10, -1, sizeof(::ModuleConfig)},
        {12, -1, -1, sizeof(::ModulesConfig)},
        {21, 47, -1, sizeof(::MultiModalFusionModelConfig)},
        {65, 75, -1, sizeof(::MultiModalFusionConfig)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::_ModuleConfig_default_instance_._instance,
    &::_ModulesConfig_default_instance_._instance,
    &::_MultiModalFusionModelConfig_default_instance_._instance,
    &::_MultiModalFusionConfig_default_instance_._instance,
};
const char descriptor_table_protodef_MultiModalFusion_5fconf_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\033MultiModalFusion_conf.proto\"*\n\014ModuleC"
    "onfig\022\014\n\004type\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\"/\n\rMod"
    "ulesConfig\022\036\n\007modules\030\001 \003(\0132\r.ModuleConf"
    "ig\"\346\002\n\033MultiModalFusionModelConfig\022\023\n\013en"
    "gine_path\030\001 \001(\t\022\021\n\tnum_class\030\002 \001(\005\022\022\n\nba"
    "tch_size\030\003 \001(\005\022\r\n\005width\030\004 \001(\005\022\016\n\006height\030"
    "\005 \001(\005\022\022\n\nconf_thres\030\006 \001(\002\022\021\n\tiou_thres\030\007"
    " \001(\002\022\016\n\006stride\030\010 \003(\005\022\021\n\tsrc_width\030\t \001(\005\022"
    "\022\n\nsrc_height\030\n \001(\005\022\024\n\014resize_ratio\030\013 \001("
    "\002\022\n\n\002dw\030\014 \001(\005\022\n\n\002dh\030\r \001(\005\022\023\n\013new_unpad_w"
    "\030\016 \001(\005\022\023\n\013new_unpad_h\030\017 \001(\005\022\020\n\010max_dets\030"
    "\020 \001(\005\022\020\n\010channels\030\022 \001(\005\022\022\n\nrun_status\030\023 "
    "\001(\010\"t\n\026MultiModalFusionConfig\0222\n\014model_c"
    "onfig\030\001 \001(\0132\034.MultiModalFusionModelConfi"
    "g\022&\n\016modules_config\030\002 \001(\0132\016.ModulesConfi"
    "gb\006proto3"
};
static ::absl::once_flag descriptor_table_MultiModalFusion_5fconf_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_MultiModalFusion_5fconf_2eproto = {
    false,
    false,
    609,
    descriptor_table_protodef_MultiModalFusion_5fconf_2eproto,
    "MultiModalFusion_conf.proto",
    &descriptor_table_MultiModalFusion_5fconf_2eproto_once,
    nullptr,
    0,
    4,
    schemas,
    file_default_instances,
    TableStruct_MultiModalFusion_5fconf_2eproto::offsets,
    file_level_enum_descriptors_MultiModalFusion_5fconf_2eproto,
    file_level_service_descriptors_MultiModalFusion_5fconf_2eproto,
};
// ===================================================================

class ModuleConfig::_Internal {
 public:
  using HasBits =
      decltype(std::declval<ModuleConfig>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(ModuleConfig, _impl_._has_bits_);
};

ModuleConfig::ModuleConfig(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ModuleConfig_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ModuleConfig)
}
PROTOBUF_NDEBUG_INLINE ModuleConfig::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::ModuleConfig& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        type_(arena, from.type_),
        name_(arena, from.name_) {}

ModuleConfig::ModuleConfig(
    ::google::protobuf::Arena* arena,
    const ModuleConfig& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ModuleConfig_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ModuleConfig* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:ModuleConfig)
}
PROTOBUF_NDEBUG_INLINE ModuleConfig::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        type_(arena),
        name_(arena) {}

inline void ModuleConfig::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
ModuleConfig::~ModuleConfig() {
  // @@protoc_insertion_point(destructor:ModuleConfig)
  SharedDtor(*this);
}
inline void ModuleConfig::SharedDtor(MessageLite& self) {
  ModuleConfig& this_ = static_cast<ModuleConfig&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.type_.Destroy();
  this_._impl_.name_.Destroy();
  this_._impl_.~Impl_();
}

inline void* ModuleConfig::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) ModuleConfig(arena);
}
constexpr auto ModuleConfig::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(ModuleConfig),
                                            alignof(ModuleConfig));
}
constexpr auto ModuleConfig::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_ModuleConfig_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &ModuleConfig::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<ModuleConfig>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &ModuleConfig::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<ModuleConfig>(), &ModuleConfig::ByteSizeLong,
              &ModuleConfig::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(ModuleConfig, _impl_._cached_size_),
          false,
      },
      &ModuleConfig::kDescriptorMethods,
      &descriptor_table_MultiModalFusion_5fconf_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const ::google::protobuf::internal::ClassDataFull
        ModuleConfig_class_data_ =
            ModuleConfig::InternalGenerateClassData_();

const ::google::protobuf::internal::ClassData* ModuleConfig::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&ModuleConfig_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(ModuleConfig_class_data_.tc_table);
  return ModuleConfig_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 29, 2> ModuleConfig::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ModuleConfig, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    ModuleConfig_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::ModuleConfig>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string name = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 1, 0, PROTOBUF_FIELD_OFFSET(ModuleConfig, _impl_.name_)}},
    // string type = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(ModuleConfig, _impl_.type_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string type = 1;
    {PROTOBUF_FIELD_OFFSET(ModuleConfig, _impl_.type_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string name = 2;
    {PROTOBUF_FIELD_OFFSET(ModuleConfig, _impl_.name_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\14\4\4\0\0\0\0\0"
    "ModuleConfig"
    "type"
    "name"
  }},
};

PROTOBUF_NOINLINE void ModuleConfig::Clear() {
// @@protoc_insertion_point(message_clear_start:ModuleConfig)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _impl_.type_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      _impl_.name_.ClearNonDefaultToEmpty();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* ModuleConfig::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const ModuleConfig& this_ = static_cast<const ModuleConfig&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* ModuleConfig::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const ModuleConfig& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:ModuleConfig)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string type = 1;
          if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
            if (!this_._internal_type().empty()) {
              const std::string& _s = this_._internal_type();
              ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                  _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "ModuleConfig.type");
              target = stream->WriteStringMaybeAliased(1, _s, target);
            }
          }

          // string name = 2;
          if ((this_._impl_._has_bits_[0] & 0x00000002u) != 0) {
            if (!this_._internal_name().empty()) {
              const std::string& _s = this_._internal_name();
              ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                  _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "ModuleConfig.name");
              target = stream->WriteStringMaybeAliased(2, _s, target);
            }
          }

          if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:ModuleConfig)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t ModuleConfig::ByteSizeLong(const MessageLite& base) {
          const ModuleConfig& this_ = static_cast<const ModuleConfig&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t ModuleConfig::ByteSizeLong() const {
          const ModuleConfig& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:ModuleConfig)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
          cached_has_bits = this_._impl_._has_bits_[0];
          if (cached_has_bits & 0x00000003u) {
            // string type = 1;
            if (cached_has_bits & 0x00000001u) {
              if (!this_._internal_type().empty()) {
                total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                                this_._internal_type());
              }
            }
            // string name = 2;
            if (cached_has_bits & 0x00000002u) {
              if (!this_._internal_name().empty()) {
                total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                                this_._internal_name());
              }
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void ModuleConfig::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ModuleConfig*>(&to_msg);
  auto& from = static_cast<const ModuleConfig&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ModuleConfig)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      if (!from._internal_type().empty()) {
        _this->_internal_set_type(from._internal_type());
      } else {
        if (_this->_impl_.type_.IsDefault()) {
          _this->_internal_set_type("");
        }
      }
    }
    if (cached_has_bits & 0x00000002u) {
      if (!from._internal_name().empty()) {
        _this->_internal_set_name(from._internal_name());
      } else {
        if (_this->_impl_.name_.IsDefault()) {
          _this->_internal_set_name("");
        }
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ModuleConfig::CopyFrom(const ModuleConfig& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ModuleConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ModuleConfig::InternalSwap(ModuleConfig* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.type_, &other->_impl_.type_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
}

::google::protobuf::Metadata ModuleConfig::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ModulesConfig::_Internal {
 public:
};

ModulesConfig::ModulesConfig(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ModulesConfig_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ModulesConfig)
}
PROTOBUF_NDEBUG_INLINE ModulesConfig::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::ModulesConfig& from_msg)
      : modules_{visibility, arena, from.modules_},
        _cached_size_{0} {}

ModulesConfig::ModulesConfig(
    ::google::protobuf::Arena* arena,
    const ModulesConfig& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ModulesConfig_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ModulesConfig* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:ModulesConfig)
}
PROTOBUF_NDEBUG_INLINE ModulesConfig::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : modules_{visibility, arena},
        _cached_size_{0} {}

inline void ModulesConfig::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
ModulesConfig::~ModulesConfig() {
  // @@protoc_insertion_point(destructor:ModulesConfig)
  SharedDtor(*this);
}
inline void ModulesConfig::SharedDtor(MessageLite& self) {
  ModulesConfig& this_ = static_cast<ModulesConfig&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* ModulesConfig::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) ModulesConfig(arena);
}
constexpr auto ModulesConfig::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(ModulesConfig, _impl_.modules_) +
          decltype(ModulesConfig::_impl_.modules_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(ModulesConfig), alignof(ModulesConfig), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&ModulesConfig::PlacementNew_,
                                 sizeof(ModulesConfig),
                                 alignof(ModulesConfig));
  }
}
constexpr auto ModulesConfig::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_ModulesConfig_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &ModulesConfig::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<ModulesConfig>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &ModulesConfig::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<ModulesConfig>(), &ModulesConfig::ByteSizeLong,
              &ModulesConfig::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(ModulesConfig, _impl_._cached_size_),
          false,
      },
      &ModulesConfig::kDescriptorMethods,
      &descriptor_table_MultiModalFusion_5fconf_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const ::google::protobuf::internal::ClassDataFull
        ModulesConfig_class_data_ =
            ModulesConfig::InternalGenerateClassData_();

const ::google::protobuf::internal::ClassData* ModulesConfig::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&ModulesConfig_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(ModulesConfig_class_data_.tc_table);
  return ModulesConfig_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2> ModulesConfig::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    ModulesConfig_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::ModulesConfig>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .ModuleConfig modules = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(ModulesConfig, _impl_.modules_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .ModuleConfig modules = 1;
    {PROTOBUF_FIELD_OFFSET(ModulesConfig, _impl_.modules_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::ModuleConfig>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void ModulesConfig::Clear() {
// @@protoc_insertion_point(message_clear_start:ModulesConfig)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.modules_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* ModulesConfig::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const ModulesConfig& this_ = static_cast<const ModulesConfig&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* ModulesConfig::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const ModulesConfig& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:ModulesConfig)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // repeated .ModuleConfig modules = 1;
          for (unsigned i = 0, n = static_cast<unsigned>(
                                   this_._internal_modules_size());
               i < n; i++) {
            const auto& repfield = this_._internal_modules().Get(i);
            target =
                ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                    1, repfield, repfield.GetCachedSize(),
                    target, stream);
          }

          if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:ModulesConfig)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t ModulesConfig::ByteSizeLong(const MessageLite& base) {
          const ModulesConfig& this_ = static_cast<const ModulesConfig&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t ModulesConfig::ByteSizeLong() const {
          const ModulesConfig& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:ModulesConfig)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated .ModuleConfig modules = 1;
            {
              total_size += 1UL * this_._internal_modules_size();
              for (const auto& msg : this_._internal_modules()) {
                total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
              }
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void ModulesConfig::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ModulesConfig*>(&to_msg);
  auto& from = static_cast<const ModulesConfig&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ModulesConfig)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_modules()->MergeFrom(
      from._internal_modules());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ModulesConfig::CopyFrom(const ModulesConfig& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ModulesConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ModulesConfig::InternalSwap(ModulesConfig* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.modules_.InternalSwap(&other->_impl_.modules_);
}

::google::protobuf::Metadata ModulesConfig::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class MultiModalFusionModelConfig::_Internal {
 public:
  using HasBits =
      decltype(std::declval<MultiModalFusionModelConfig>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(MultiModalFusionModelConfig, _impl_._has_bits_);
};

MultiModalFusionModelConfig::MultiModalFusionModelConfig(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, MultiModalFusionModelConfig_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:MultiModalFusionModelConfig)
}
PROTOBUF_NDEBUG_INLINE MultiModalFusionModelConfig::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::MultiModalFusionModelConfig& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        stride_{visibility, arena, from.stride_},
        _stride_cached_byte_size_{0},
        engine_path_(arena, from.engine_path_) {}

MultiModalFusionModelConfig::MultiModalFusionModelConfig(
    ::google::protobuf::Arena* arena,
    const MultiModalFusionModelConfig& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, MultiModalFusionModelConfig_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  MultiModalFusionModelConfig* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, num_class_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, num_class_),
           offsetof(Impl_, run_status_) -
               offsetof(Impl_, num_class_) +
               sizeof(Impl_::run_status_));

  // @@protoc_insertion_point(copy_constructor:MultiModalFusionModelConfig)
}
PROTOBUF_NDEBUG_INLINE MultiModalFusionModelConfig::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        stride_{visibility, arena},
        _stride_cached_byte_size_{0},
        engine_path_(arena) {}

inline void MultiModalFusionModelConfig::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, num_class_),
           0,
           offsetof(Impl_, run_status_) -
               offsetof(Impl_, num_class_) +
               sizeof(Impl_::run_status_));
}
MultiModalFusionModelConfig::~MultiModalFusionModelConfig() {
  // @@protoc_insertion_point(destructor:MultiModalFusionModelConfig)
  SharedDtor(*this);
}
inline void MultiModalFusionModelConfig::SharedDtor(MessageLite& self) {
  MultiModalFusionModelConfig& this_ = static_cast<MultiModalFusionModelConfig&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.engine_path_.Destroy();
  this_._impl_.~Impl_();
}

inline void* MultiModalFusionModelConfig::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) MultiModalFusionModelConfig(arena);
}
constexpr auto MultiModalFusionModelConfig::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(MultiModalFusionModelConfig, _impl_.stride_) +
          decltype(MultiModalFusionModelConfig::_impl_.stride_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(MultiModalFusionModelConfig), alignof(MultiModalFusionModelConfig), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&MultiModalFusionModelConfig::PlacementNew_,
                                 sizeof(MultiModalFusionModelConfig),
                                 alignof(MultiModalFusionModelConfig));
  }
}
constexpr auto MultiModalFusionModelConfig::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_MultiModalFusionModelConfig_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &MultiModalFusionModelConfig::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<MultiModalFusionModelConfig>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &MultiModalFusionModelConfig::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<MultiModalFusionModelConfig>(), &MultiModalFusionModelConfig::ByteSizeLong,
              &MultiModalFusionModelConfig::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(MultiModalFusionModelConfig, _impl_._cached_size_),
          false,
      },
      &MultiModalFusionModelConfig::kDescriptorMethods,
      &descriptor_table_MultiModalFusion_5fconf_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const ::google::protobuf::internal::ClassDataFull
        MultiModalFusionModelConfig_class_data_ =
            MultiModalFusionModelConfig::InternalGenerateClassData_();

const ::google::protobuf::internal::ClassData* MultiModalFusionModelConfig::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&MultiModalFusionModelConfig_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(MultiModalFusionModelConfig_class_data_.tc_table);
  return MultiModalFusionModelConfig_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<5, 18, 0, 63, 2> MultiModalFusionModelConfig::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(MultiModalFusionModelConfig, _impl_._has_bits_),
    0, // no _extensions_
    19, 248,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294508544,  // skipmap
    offsetof(decltype(_table_), field_entries),
    18,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    MultiModalFusionModelConfig_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::MultiModalFusionModelConfig>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string engine_path = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(MultiModalFusionModelConfig, _impl_.engine_path_)}},
    // int32 num_class = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(MultiModalFusionModelConfig, _impl_.num_class_), 1>(),
     {16, 1, 0, PROTOBUF_FIELD_OFFSET(MultiModalFusionModelConfig, _impl_.num_class_)}},
    // int32 batch_size = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(MultiModalFusionModelConfig, _impl_.batch_size_), 2>(),
     {24, 2, 0, PROTOBUF_FIELD_OFFSET(MultiModalFusionModelConfig, _impl_.batch_size_)}},
    // int32 width = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(MultiModalFusionModelConfig, _impl_.width_), 3>(),
     {32, 3, 0, PROTOBUF_FIELD_OFFSET(MultiModalFusionModelConfig, _impl_.width_)}},
    // int32 height = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(MultiModalFusionModelConfig, _impl_.height_), 4>(),
     {40, 4, 0, PROTOBUF_FIELD_OFFSET(MultiModalFusionModelConfig, _impl_.height_)}},
    // float conf_thres = 6;
    {::_pbi::TcParser::FastF32S1,
     {53, 5, 0, PROTOBUF_FIELD_OFFSET(MultiModalFusionModelConfig, _impl_.conf_thres_)}},
    // float iou_thres = 7;
    {::_pbi::TcParser::FastF32S1,
     {61, 6, 0, PROTOBUF_FIELD_OFFSET(MultiModalFusionModelConfig, _impl_.iou_thres_)}},
    // repeated int32 stride = 8;
    {::_pbi::TcParser::FastV32P1,
     {66, 63, 0, PROTOBUF_FIELD_OFFSET(MultiModalFusionModelConfig, _impl_.stride_)}},
    // int32 src_width = 9;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(MultiModalFusionModelConfig, _impl_.src_width_), 7>(),
     {72, 7, 0, PROTOBUF_FIELD_OFFSET(MultiModalFusionModelConfig, _impl_.src_width_)}},
    // int32 src_height = 10;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(MultiModalFusionModelConfig, _impl_.src_height_), 8>(),
     {80, 8, 0, PROTOBUF_FIELD_OFFSET(MultiModalFusionModelConfig, _impl_.src_height_)}},
    // float resize_ratio = 11;
    {::_pbi::TcParser::FastF32S1,
     {93, 9, 0, PROTOBUF_FIELD_OFFSET(MultiModalFusionModelConfig, _impl_.resize_ratio_)}},
    // int32 dw = 12;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(MultiModalFusionModelConfig, _impl_.dw_), 10>(),
     {96, 10, 0, PROTOBUF_FIELD_OFFSET(MultiModalFusionModelConfig, _impl_.dw_)}},
    // int32 dh = 13;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(MultiModalFusionModelConfig, _impl_.dh_), 11>(),
     {104, 11, 0, PROTOBUF_FIELD_OFFSET(MultiModalFusionModelConfig, _impl_.dh_)}},
    // int32 new_unpad_w = 14;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(MultiModalFusionModelConfig, _impl_.new_unpad_w_), 12>(),
     {112, 12, 0, PROTOBUF_FIELD_OFFSET(MultiModalFusionModelConfig, _impl_.new_unpad_w_)}},
    // int32 new_unpad_h = 15;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(MultiModalFusionModelConfig, _impl_.new_unpad_h_), 13>(),
     {120, 13, 0, PROTOBUF_FIELD_OFFSET(MultiModalFusionModelConfig, _impl_.new_unpad_h_)}},
    // int32 max_dets = 16;
    {::_pbi::TcParser::FastV32S2,
     {384, 14, 0, PROTOBUF_FIELD_OFFSET(MultiModalFusionModelConfig, _impl_.max_dets_)}},
    {::_pbi::TcParser::MiniParse, {}},
    // int32 channels = 18;
    {::_pbi::TcParser::FastV32S2,
     {400, 15, 0, PROTOBUF_FIELD_OFFSET(MultiModalFusionModelConfig, _impl_.channels_)}},
    // bool run_status = 19;
    {::_pbi::TcParser::FastV8S2,
     {408, 16, 0, PROTOBUF_FIELD_OFFSET(MultiModalFusionModelConfig, _impl_.run_status_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // string engine_path = 1;
    {PROTOBUF_FIELD_OFFSET(MultiModalFusionModelConfig, _impl_.engine_path_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int32 num_class = 2;
    {PROTOBUF_FIELD_OFFSET(MultiModalFusionModelConfig, _impl_.num_class_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // int32 batch_size = 3;
    {PROTOBUF_FIELD_OFFSET(MultiModalFusionModelConfig, _impl_.batch_size_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // int32 width = 4;
    {PROTOBUF_FIELD_OFFSET(MultiModalFusionModelConfig, _impl_.width_), _Internal::kHasBitsOffset + 3, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // int32 height = 5;
    {PROTOBUF_FIELD_OFFSET(MultiModalFusionModelConfig, _impl_.height_), _Internal::kHasBitsOffset + 4, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // float conf_thres = 6;
    {PROTOBUF_FIELD_OFFSET(MultiModalFusionModelConfig, _impl_.conf_thres_), _Internal::kHasBitsOffset + 5, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
    // float iou_thres = 7;
    {PROTOBUF_FIELD_OFFSET(MultiModalFusionModelConfig, _impl_.iou_thres_), _Internal::kHasBitsOffset + 6, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
    // repeated int32 stride = 8;
    {PROTOBUF_FIELD_OFFSET(MultiModalFusionModelConfig, _impl_.stride_), -1, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedInt32)},
    // int32 src_width = 9;
    {PROTOBUF_FIELD_OFFSET(MultiModalFusionModelConfig, _impl_.src_width_), _Internal::kHasBitsOffset + 7, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // int32 src_height = 10;
    {PROTOBUF_FIELD_OFFSET(MultiModalFusionModelConfig, _impl_.src_height_), _Internal::kHasBitsOffset + 8, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // float resize_ratio = 11;
    {PROTOBUF_FIELD_OFFSET(MultiModalFusionModelConfig, _impl_.resize_ratio_), _Internal::kHasBitsOffset + 9, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
    // int32 dw = 12;
    {PROTOBUF_FIELD_OFFSET(MultiModalFusionModelConfig, _impl_.dw_), _Internal::kHasBitsOffset + 10, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // int32 dh = 13;
    {PROTOBUF_FIELD_OFFSET(MultiModalFusionModelConfig, _impl_.dh_), _Internal::kHasBitsOffset + 11, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // int32 new_unpad_w = 14;
    {PROTOBUF_FIELD_OFFSET(MultiModalFusionModelConfig, _impl_.new_unpad_w_), _Internal::kHasBitsOffset + 12, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // int32 new_unpad_h = 15;
    {PROTOBUF_FIELD_OFFSET(MultiModalFusionModelConfig, _impl_.new_unpad_h_), _Internal::kHasBitsOffset + 13, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // int32 max_dets = 16;
    {PROTOBUF_FIELD_OFFSET(MultiModalFusionModelConfig, _impl_.max_dets_), _Internal::kHasBitsOffset + 14, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // int32 channels = 18;
    {PROTOBUF_FIELD_OFFSET(MultiModalFusionModelConfig, _impl_.channels_), _Internal::kHasBitsOffset + 15, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // bool run_status = 19;
    {PROTOBUF_FIELD_OFFSET(MultiModalFusionModelConfig, _impl_.run_status_), _Internal::kHasBitsOffset + 16, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
    "\33\13\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"
    "MultiModalFusionModelConfig"
    "engine_path"
  }},
};

PROTOBUF_NOINLINE void MultiModalFusionModelConfig::Clear() {
// @@protoc_insertion_point(message_clear_start:MultiModalFusionModelConfig)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.stride_.Clear();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    _impl_.engine_path_.ClearNonDefaultToEmpty();
  }
  if (cached_has_bits & 0x000000feu) {
    ::memset(&_impl_.num_class_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.src_width_) -
        reinterpret_cast<char*>(&_impl_.num_class_)) + sizeof(_impl_.src_width_));
  }
  if (cached_has_bits & 0x0000ff00u) {
    ::memset(&_impl_.src_height_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.channels_) -
        reinterpret_cast<char*>(&_impl_.src_height_)) + sizeof(_impl_.channels_));
  }
  _impl_.run_status_ = false;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* MultiModalFusionModelConfig::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const MultiModalFusionModelConfig& this_ = static_cast<const MultiModalFusionModelConfig&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* MultiModalFusionModelConfig::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const MultiModalFusionModelConfig& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:MultiModalFusionModelConfig)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string engine_path = 1;
          if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
            if (!this_._internal_engine_path().empty()) {
              const std::string& _s = this_._internal_engine_path();
              ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                  _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "MultiModalFusionModelConfig.engine_path");
              target = stream->WriteStringMaybeAliased(1, _s, target);
            }
          }

          // int32 num_class = 2;
          if ((this_._impl_._has_bits_[0] & 0x00000002u) != 0) {
            if (this_._internal_num_class() != 0) {
              target = ::google::protobuf::internal::WireFormatLite::
                  WriteInt32ToArrayWithField<2>(
                      stream, this_._internal_num_class(), target);
            }
          }

          // int32 batch_size = 3;
          if ((this_._impl_._has_bits_[0] & 0x00000004u) != 0) {
            if (this_._internal_batch_size() != 0) {
              target = ::google::protobuf::internal::WireFormatLite::
                  WriteInt32ToArrayWithField<3>(
                      stream, this_._internal_batch_size(), target);
            }
          }

          // int32 width = 4;
          if ((this_._impl_._has_bits_[0] & 0x00000008u) != 0) {
            if (this_._internal_width() != 0) {
              target = ::google::protobuf::internal::WireFormatLite::
                  WriteInt32ToArrayWithField<4>(
                      stream, this_._internal_width(), target);
            }
          }

          // int32 height = 5;
          if ((this_._impl_._has_bits_[0] & 0x00000010u) != 0) {
            if (this_._internal_height() != 0) {
              target = ::google::protobuf::internal::WireFormatLite::
                  WriteInt32ToArrayWithField<5>(
                      stream, this_._internal_height(), target);
            }
          }

          // float conf_thres = 6;
          if ((this_._impl_._has_bits_[0] & 0x00000020u) != 0) {
            if (::absl::bit_cast<::uint32_t>(this_._internal_conf_thres()) != 0) {
              target = stream->EnsureSpace(target);
              target = ::_pbi::WireFormatLite::WriteFloatToArray(
                  6, this_._internal_conf_thres(), target);
            }
          }

          // float iou_thres = 7;
          if ((this_._impl_._has_bits_[0] & 0x00000040u) != 0) {
            if (::absl::bit_cast<::uint32_t>(this_._internal_iou_thres()) != 0) {
              target = stream->EnsureSpace(target);
              target = ::_pbi::WireFormatLite::WriteFloatToArray(
                  7, this_._internal_iou_thres(), target);
            }
          }

          // repeated int32 stride = 8;
          {
            int byte_size = this_._impl_._stride_cached_byte_size_.Get();
            if (byte_size > 0) {
              target = stream->WriteInt32Packed(
                  8, this_._internal_stride(), byte_size, target);
            }
          }

          // int32 src_width = 9;
          if ((this_._impl_._has_bits_[0] & 0x00000080u) != 0) {
            if (this_._internal_src_width() != 0) {
              target = ::google::protobuf::internal::WireFormatLite::
                  WriteInt32ToArrayWithField<9>(
                      stream, this_._internal_src_width(), target);
            }
          }

          // int32 src_height = 10;
          if ((this_._impl_._has_bits_[0] & 0x00000100u) != 0) {
            if (this_._internal_src_height() != 0) {
              target = ::google::protobuf::internal::WireFormatLite::
                  WriteInt32ToArrayWithField<10>(
                      stream, this_._internal_src_height(), target);
            }
          }

          // float resize_ratio = 11;
          if ((this_._impl_._has_bits_[0] & 0x00000200u) != 0) {
            if (::absl::bit_cast<::uint32_t>(this_._internal_resize_ratio()) != 0) {
              target = stream->EnsureSpace(target);
              target = ::_pbi::WireFormatLite::WriteFloatToArray(
                  11, this_._internal_resize_ratio(), target);
            }
          }

          // int32 dw = 12;
          if ((this_._impl_._has_bits_[0] & 0x00000400u) != 0) {
            if (this_._internal_dw() != 0) {
              target = ::google::protobuf::internal::WireFormatLite::
                  WriteInt32ToArrayWithField<12>(
                      stream, this_._internal_dw(), target);
            }
          }

          // int32 dh = 13;
          if ((this_._impl_._has_bits_[0] & 0x00000800u) != 0) {
            if (this_._internal_dh() != 0) {
              target = ::google::protobuf::internal::WireFormatLite::
                  WriteInt32ToArrayWithField<13>(
                      stream, this_._internal_dh(), target);
            }
          }

          // int32 new_unpad_w = 14;
          if ((this_._impl_._has_bits_[0] & 0x00001000u) != 0) {
            if (this_._internal_new_unpad_w() != 0) {
              target = ::google::protobuf::internal::WireFormatLite::
                  WriteInt32ToArrayWithField<14>(
                      stream, this_._internal_new_unpad_w(), target);
            }
          }

          // int32 new_unpad_h = 15;
          if ((this_._impl_._has_bits_[0] & 0x00002000u) != 0) {
            if (this_._internal_new_unpad_h() != 0) {
              target = ::google::protobuf::internal::WireFormatLite::
                  WriteInt32ToArrayWithField<15>(
                      stream, this_._internal_new_unpad_h(), target);
            }
          }

          // int32 max_dets = 16;
          if ((this_._impl_._has_bits_[0] & 0x00004000u) != 0) {
            if (this_._internal_max_dets() != 0) {
              target = stream->EnsureSpace(target);
              target = ::_pbi::WireFormatLite::WriteInt32ToArray(
                  16, this_._internal_max_dets(), target);
            }
          }

          // int32 channels = 18;
          if ((this_._impl_._has_bits_[0] & 0x00008000u) != 0) {
            if (this_._internal_channels() != 0) {
              target = stream->EnsureSpace(target);
              target = ::_pbi::WireFormatLite::WriteInt32ToArray(
                  18, this_._internal_channels(), target);
            }
          }

          // bool run_status = 19;
          if ((this_._impl_._has_bits_[0] & 0x00010000u) != 0) {
            if (this_._internal_run_status() != 0) {
              target = stream->EnsureSpace(target);
              target = ::_pbi::WireFormatLite::WriteBoolToArray(
                  19, this_._internal_run_status(), target);
            }
          }

          if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:MultiModalFusionModelConfig)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t MultiModalFusionModelConfig::ByteSizeLong(const MessageLite& base) {
          const MultiModalFusionModelConfig& this_ = static_cast<const MultiModalFusionModelConfig&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t MultiModalFusionModelConfig::ByteSizeLong() const {
          const MultiModalFusionModelConfig& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:MultiModalFusionModelConfig)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated int32 stride = 8;
            {
              total_size +=
                  ::_pbi::WireFormatLite::Int32SizeWithPackedTagSize(
                      this_._internal_stride(), 1,
                      this_._impl_._stride_cached_byte_size_);
            }
          }
          cached_has_bits = this_._impl_._has_bits_[0];
          if (cached_has_bits & 0x000000ffu) {
            // string engine_path = 1;
            if (cached_has_bits & 0x00000001u) {
              if (!this_._internal_engine_path().empty()) {
                total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                                this_._internal_engine_path());
              }
            }
            // int32 num_class = 2;
            if (cached_has_bits & 0x00000002u) {
              if (this_._internal_num_class() != 0) {
                total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                    this_._internal_num_class());
              }
            }
            // int32 batch_size = 3;
            if (cached_has_bits & 0x00000004u) {
              if (this_._internal_batch_size() != 0) {
                total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                    this_._internal_batch_size());
              }
            }
            // int32 width = 4;
            if (cached_has_bits & 0x00000008u) {
              if (this_._internal_width() != 0) {
                total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                    this_._internal_width());
              }
            }
            // int32 height = 5;
            if (cached_has_bits & 0x00000010u) {
              if (this_._internal_height() != 0) {
                total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                    this_._internal_height());
              }
            }
            // float conf_thres = 6;
            if (cached_has_bits & 0x00000020u) {
              if (::absl::bit_cast<::uint32_t>(this_._internal_conf_thres()) != 0) {
                total_size += 5;
              }
            }
            // float iou_thres = 7;
            if (cached_has_bits & 0x00000040u) {
              if (::absl::bit_cast<::uint32_t>(this_._internal_iou_thres()) != 0) {
                total_size += 5;
              }
            }
            // int32 src_width = 9;
            if (cached_has_bits & 0x00000080u) {
              if (this_._internal_src_width() != 0) {
                total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                    this_._internal_src_width());
              }
            }
          }
          if (cached_has_bits & 0x0000ff00u) {
            // int32 src_height = 10;
            if (cached_has_bits & 0x00000100u) {
              if (this_._internal_src_height() != 0) {
                total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                    this_._internal_src_height());
              }
            }
            // float resize_ratio = 11;
            if (cached_has_bits & 0x00000200u) {
              if (::absl::bit_cast<::uint32_t>(this_._internal_resize_ratio()) != 0) {
                total_size += 5;
              }
            }
            // int32 dw = 12;
            if (cached_has_bits & 0x00000400u) {
              if (this_._internal_dw() != 0) {
                total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                    this_._internal_dw());
              }
            }
            // int32 dh = 13;
            if (cached_has_bits & 0x00000800u) {
              if (this_._internal_dh() != 0) {
                total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                    this_._internal_dh());
              }
            }
            // int32 new_unpad_w = 14;
            if (cached_has_bits & 0x00001000u) {
              if (this_._internal_new_unpad_w() != 0) {
                total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                    this_._internal_new_unpad_w());
              }
            }
            // int32 new_unpad_h = 15;
            if (cached_has_bits & 0x00002000u) {
              if (this_._internal_new_unpad_h() != 0) {
                total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                    this_._internal_new_unpad_h());
              }
            }
            // int32 max_dets = 16;
            if (cached_has_bits & 0x00004000u) {
              if (this_._internal_max_dets() != 0) {
                total_size += 2 + ::_pbi::WireFormatLite::Int32Size(
                                                this_._internal_max_dets());
              }
            }
            // int32 channels = 18;
            if (cached_has_bits & 0x00008000u) {
              if (this_._internal_channels() != 0) {
                total_size += 2 + ::_pbi::WireFormatLite::Int32Size(
                                                this_._internal_channels());
              }
            }
          }
           {
            // bool run_status = 19;
            if (cached_has_bits & 0x00010000u) {
              if (this_._internal_run_status() != 0) {
                total_size += 3;
              }
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void MultiModalFusionModelConfig::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<MultiModalFusionModelConfig*>(&to_msg);
  auto& from = static_cast<const MultiModalFusionModelConfig&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:MultiModalFusionModelConfig)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_stride()->MergeFrom(from._internal_stride());
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x000000ffu) {
    if (cached_has_bits & 0x00000001u) {
      if (!from._internal_engine_path().empty()) {
        _this->_internal_set_engine_path(from._internal_engine_path());
      } else {
        if (_this->_impl_.engine_path_.IsDefault()) {
          _this->_internal_set_engine_path("");
        }
      }
    }
    if (cached_has_bits & 0x00000002u) {
      if (from._internal_num_class() != 0) {
        _this->_impl_.num_class_ = from._impl_.num_class_;
      }
    }
    if (cached_has_bits & 0x00000004u) {
      if (from._internal_batch_size() != 0) {
        _this->_impl_.batch_size_ = from._impl_.batch_size_;
      }
    }
    if (cached_has_bits & 0x00000008u) {
      if (from._internal_width() != 0) {
        _this->_impl_.width_ = from._impl_.width_;
      }
    }
    if (cached_has_bits & 0x00000010u) {
      if (from._internal_height() != 0) {
        _this->_impl_.height_ = from._impl_.height_;
      }
    }
    if (cached_has_bits & 0x00000020u) {
      if (::absl::bit_cast<::uint32_t>(from._internal_conf_thres()) != 0) {
        _this->_impl_.conf_thres_ = from._impl_.conf_thres_;
      }
    }
    if (cached_has_bits & 0x00000040u) {
      if (::absl::bit_cast<::uint32_t>(from._internal_iou_thres()) != 0) {
        _this->_impl_.iou_thres_ = from._impl_.iou_thres_;
      }
    }
    if (cached_has_bits & 0x00000080u) {
      if (from._internal_src_width() != 0) {
        _this->_impl_.src_width_ = from._impl_.src_width_;
      }
    }
  }
  if (cached_has_bits & 0x0000ff00u) {
    if (cached_has_bits & 0x00000100u) {
      if (from._internal_src_height() != 0) {
        _this->_impl_.src_height_ = from._impl_.src_height_;
      }
    }
    if (cached_has_bits & 0x00000200u) {
      if (::absl::bit_cast<::uint32_t>(from._internal_resize_ratio()) != 0) {
        _this->_impl_.resize_ratio_ = from._impl_.resize_ratio_;
      }
    }
    if (cached_has_bits & 0x00000400u) {
      if (from._internal_dw() != 0) {
        _this->_impl_.dw_ = from._impl_.dw_;
      }
    }
    if (cached_has_bits & 0x00000800u) {
      if (from._internal_dh() != 0) {
        _this->_impl_.dh_ = from._impl_.dh_;
      }
    }
    if (cached_has_bits & 0x00001000u) {
      if (from._internal_new_unpad_w() != 0) {
        _this->_impl_.new_unpad_w_ = from._impl_.new_unpad_w_;
      }
    }
    if (cached_has_bits & 0x00002000u) {
      if (from._internal_new_unpad_h() != 0) {
        _this->_impl_.new_unpad_h_ = from._impl_.new_unpad_h_;
      }
    }
    if (cached_has_bits & 0x00004000u) {
      if (from._internal_max_dets() != 0) {
        _this->_impl_.max_dets_ = from._impl_.max_dets_;
      }
    }
    if (cached_has_bits & 0x00008000u) {
      if (from._internal_channels() != 0) {
        _this->_impl_.channels_ = from._impl_.channels_;
      }
    }
  }
  if (cached_has_bits & 0x00010000u) {
    if (from._internal_run_status() != 0) {
      _this->_impl_.run_status_ = from._impl_.run_status_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void MultiModalFusionModelConfig::CopyFrom(const MultiModalFusionModelConfig& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MultiModalFusionModelConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void MultiModalFusionModelConfig::InternalSwap(MultiModalFusionModelConfig* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.stride_.InternalSwap(&other->_impl_.stride_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.engine_path_, &other->_impl_.engine_path_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(MultiModalFusionModelConfig, _impl_.run_status_)
      + sizeof(MultiModalFusionModelConfig::_impl_.run_status_)
      - PROTOBUF_FIELD_OFFSET(MultiModalFusionModelConfig, _impl_.num_class_)>(
          reinterpret_cast<char*>(&_impl_.num_class_),
          reinterpret_cast<char*>(&other->_impl_.num_class_));
}

::google::protobuf::Metadata MultiModalFusionModelConfig::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class MultiModalFusionConfig::_Internal {
 public:
  using HasBits =
      decltype(std::declval<MultiModalFusionConfig>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(MultiModalFusionConfig, _impl_._has_bits_);
};

MultiModalFusionConfig::MultiModalFusionConfig(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, MultiModalFusionConfig_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:MultiModalFusionConfig)
}
PROTOBUF_NDEBUG_INLINE MultiModalFusionConfig::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::MultiModalFusionConfig& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

MultiModalFusionConfig::MultiModalFusionConfig(
    ::google::protobuf::Arena* arena,
    const MultiModalFusionConfig& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, MultiModalFusionConfig_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  MultiModalFusionConfig* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.model_config_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::MultiModalFusionModelConfig>(
                              arena, *from._impl_.model_config_)
                        : nullptr;
  _impl_.modules_config_ = (cached_has_bits & 0x00000002u) ? ::google::protobuf::Message::CopyConstruct<::ModulesConfig>(
                              arena, *from._impl_.modules_config_)
                        : nullptr;

  // @@protoc_insertion_point(copy_constructor:MultiModalFusionConfig)
}
PROTOBUF_NDEBUG_INLINE MultiModalFusionConfig::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void MultiModalFusionConfig::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, model_config_),
           0,
           offsetof(Impl_, modules_config_) -
               offsetof(Impl_, model_config_) +
               sizeof(Impl_::modules_config_));
}
MultiModalFusionConfig::~MultiModalFusionConfig() {
  // @@protoc_insertion_point(destructor:MultiModalFusionConfig)
  SharedDtor(*this);
}
inline void MultiModalFusionConfig::SharedDtor(MessageLite& self) {
  MultiModalFusionConfig& this_ = static_cast<MultiModalFusionConfig&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.model_config_;
  delete this_._impl_.modules_config_;
  this_._impl_.~Impl_();
}

inline void* MultiModalFusionConfig::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) MultiModalFusionConfig(arena);
}
constexpr auto MultiModalFusionConfig::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(MultiModalFusionConfig),
                                            alignof(MultiModalFusionConfig));
}
constexpr auto MultiModalFusionConfig::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_MultiModalFusionConfig_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &MultiModalFusionConfig::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<MultiModalFusionConfig>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &MultiModalFusionConfig::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<MultiModalFusionConfig>(), &MultiModalFusionConfig::ByteSizeLong,
              &MultiModalFusionConfig::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(MultiModalFusionConfig, _impl_._cached_size_),
          false,
      },
      &MultiModalFusionConfig::kDescriptorMethods,
      &descriptor_table_MultiModalFusion_5fconf_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const ::google::protobuf::internal::ClassDataFull
        MultiModalFusionConfig_class_data_ =
            MultiModalFusionConfig::InternalGenerateClassData_();

const ::google::protobuf::internal::ClassData* MultiModalFusionConfig::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&MultiModalFusionConfig_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(MultiModalFusionConfig_class_data_.tc_table);
  return MultiModalFusionConfig_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 2, 0, 2> MultiModalFusionConfig::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(MultiModalFusionConfig, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    MultiModalFusionConfig_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::MultiModalFusionConfig>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .ModulesConfig modules_config = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 1, 1, PROTOBUF_FIELD_OFFSET(MultiModalFusionConfig, _impl_.modules_config_)}},
    // .MultiModalFusionModelConfig model_config = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(MultiModalFusionConfig, _impl_.model_config_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .MultiModalFusionModelConfig model_config = 1;
    {PROTOBUF_FIELD_OFFSET(MultiModalFusionConfig, _impl_.model_config_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .ModulesConfig modules_config = 2;
    {PROTOBUF_FIELD_OFFSET(MultiModalFusionConfig, _impl_.modules_config_), _Internal::kHasBitsOffset + 1, 1,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::MultiModalFusionModelConfig>()},
    {::_pbi::TcParser::GetTable<::ModulesConfig>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void MultiModalFusionConfig::Clear() {
// @@protoc_insertion_point(message_clear_start:MultiModalFusionConfig)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(_impl_.model_config_ != nullptr);
      _impl_.model_config_->Clear();
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(_impl_.modules_config_ != nullptr);
      _impl_.modules_config_->Clear();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* MultiModalFusionConfig::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const MultiModalFusionConfig& this_ = static_cast<const MultiModalFusionConfig&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* MultiModalFusionConfig::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const MultiModalFusionConfig& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:MultiModalFusionConfig)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          cached_has_bits = this_._impl_._has_bits_[0];
          // .MultiModalFusionModelConfig model_config = 1;
          if (cached_has_bits & 0x00000001u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                1, *this_._impl_.model_config_, this_._impl_.model_config_->GetCachedSize(), target,
                stream);
          }

          // .ModulesConfig modules_config = 2;
          if (cached_has_bits & 0x00000002u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                2, *this_._impl_.modules_config_, this_._impl_.modules_config_->GetCachedSize(), target,
                stream);
          }

          if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:MultiModalFusionConfig)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t MultiModalFusionConfig::ByteSizeLong(const MessageLite& base) {
          const MultiModalFusionConfig& this_ = static_cast<const MultiModalFusionConfig&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t MultiModalFusionConfig::ByteSizeLong() const {
          const MultiModalFusionConfig& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:MultiModalFusionConfig)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
          cached_has_bits = this_._impl_._has_bits_[0];
          if (cached_has_bits & 0x00000003u) {
            // .MultiModalFusionModelConfig model_config = 1;
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.model_config_);
            }
            // .ModulesConfig modules_config = 2;
            if (cached_has_bits & 0x00000002u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.modules_config_);
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void MultiModalFusionConfig::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<MultiModalFusionConfig*>(&to_msg);
  auto& from = static_cast<const MultiModalFusionConfig&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:MultiModalFusionConfig)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(from._impl_.model_config_ != nullptr);
      if (_this->_impl_.model_config_ == nullptr) {
        _this->_impl_.model_config_ =
            ::google::protobuf::Message::CopyConstruct<::MultiModalFusionModelConfig>(arena, *from._impl_.model_config_);
      } else {
        _this->_impl_.model_config_->MergeFrom(*from._impl_.model_config_);
      }
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(from._impl_.modules_config_ != nullptr);
      if (_this->_impl_.modules_config_ == nullptr) {
        _this->_impl_.modules_config_ =
            ::google::protobuf::Message::CopyConstruct<::ModulesConfig>(arena, *from._impl_.modules_config_);
      } else {
        _this->_impl_.modules_config_->MergeFrom(*from._impl_.modules_config_);
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void MultiModalFusionConfig::CopyFrom(const MultiModalFusionConfig& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MultiModalFusionConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void MultiModalFusionConfig::InternalSwap(MultiModalFusionConfig* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(MultiModalFusionConfig, _impl_.modules_config_)
      + sizeof(MultiModalFusionConfig::_impl_.modules_config_)
      - PROTOBUF_FIELD_OFFSET(MultiModalFusionConfig, _impl_.model_config_)>(
          reinterpret_cast<char*>(&_impl_.model_config_),
          reinterpret_cast<char*>(&other->_impl_.model_config_));
}

::google::protobuf::Metadata MultiModalFusionConfig::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_MultiModalFusion_5fconf_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
