// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ObjectLocation_conf.proto
// Protobuf C++ Version: 5.30.0-dev

#ifndef ObjectLocation_5fconf_2eproto_2epb_2eh
#define ObjectLocation_5fconf_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5030000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "AlgorithmConfig_conf.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_ObjectLocation_5fconf_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_ObjectLocation_5fconf_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_ObjectLocation_5fconf_2eproto;
namespace objectlocation {
class ObjectLocationConfig;
struct ObjectLocationConfigDefaultTypeInternal;
extern ObjectLocationConfigDefaultTypeInternal _ObjectLocationConfig_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull ObjectLocationConfig_class_data_;
class TaskConfig;
struct TaskConfigDefaultTypeInternal;
extern TaskConfigDefaultTypeInternal _TaskConfig_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull TaskConfig_class_data_;
}  // namespace objectlocation
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace objectlocation {

// ===================================================================


// -------------------------------------------------------------------

class TaskConfig final
    : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:objectlocation.TaskConfig) */ {
 public:
  inline TaskConfig() : TaskConfig(nullptr) {}
  ~TaskConfig() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(TaskConfig* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(TaskConfig));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR TaskConfig(
      ::google::protobuf::internal::ConstantInitialized);

  inline TaskConfig(const TaskConfig& from) : TaskConfig(nullptr, from) {}
  inline TaskConfig(TaskConfig&& from) noexcept
      : TaskConfig(nullptr, std::move(from)) {}
  inline TaskConfig& operator=(const TaskConfig& from) {
    CopyFrom(from);
    return *this;
  }
  inline TaskConfig& operator=(TaskConfig&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TaskConfig& default_instance() {
    return *internal_default_instance();
  }
  static inline const TaskConfig* internal_default_instance() {
    return reinterpret_cast<const TaskConfig*>(
        &_TaskConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(TaskConfig& a, TaskConfig& b) { a.Swap(&b); }
  inline void Swap(TaskConfig* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TaskConfig* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TaskConfig* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<TaskConfig>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const TaskConfig& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const TaskConfig& from) { TaskConfig::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(TaskConfig* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "objectlocation.TaskConfig"; }

 protected:
  explicit TaskConfig(::google::protobuf::Arena* arena);
  TaskConfig(::google::protobuf::Arena* arena, const TaskConfig& from);
  TaskConfig(::google::protobuf::Arena* arena, TaskConfig&& from) noexcept
      : TaskConfig(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kStrideFieldNumber = 8,
    kEnginePathFieldNumber = 1,
    kNumClassFieldNumber = 2,
    kBatchSizeFieldNumber = 3,
    kWidthFieldNumber = 4,
    kHeightFieldNumber = 5,
    kConfThresFieldNumber = 6,
    kIouThresFieldNumber = 7,
    kSrcWidthFieldNumber = 9,
    kSrcHeightFieldNumber = 10,
    kResizeRatioFieldNumber = 11,
    kDwFieldNumber = 12,
    kDhFieldNumber = 13,
    kNewUnpadWFieldNumber = 14,
    kNewUnpadHFieldNumber = 15,
    kMaxDetsFieldNumber = 16,
    kNumKeysFieldNumber = 17,
    kChannelsFieldNumber = 18,
    kRunStatusFieldNumber = 19,
  };
  // repeated int32 stride = 8;
  int stride_size() const;
  private:
  int _internal_stride_size() const;

  public:
  void clear_stride() ;
  ::int32_t stride(int index) const;
  void set_stride(int index, ::int32_t value);
  void add_stride(::int32_t value);
  const ::google::protobuf::RepeatedField<::int32_t>& stride() const;
  ::google::protobuf::RepeatedField<::int32_t>* mutable_stride();

  private:
  const ::google::protobuf::RepeatedField<::int32_t>& _internal_stride() const;
  ::google::protobuf::RepeatedField<::int32_t>* _internal_mutable_stride();

  public:
  // string engine_path = 1;
  void clear_engine_path() ;
  const std::string& engine_path() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_engine_path(Arg_&& arg, Args_... args);
  std::string* mutable_engine_path();
  [[nodiscard]] std::string* release_engine_path();
  void set_allocated_engine_path(std::string* value);

  private:
  const std::string& _internal_engine_path() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_engine_path(const std::string& value);
  std::string* _internal_mutable_engine_path();

  public:
  // int32 num_class = 2;
  void clear_num_class() ;
  ::int32_t num_class() const;
  void set_num_class(::int32_t value);

  private:
  ::int32_t _internal_num_class() const;
  void _internal_set_num_class(::int32_t value);

  public:
  // int32 batch_size = 3;
  void clear_batch_size() ;
  ::int32_t batch_size() const;
  void set_batch_size(::int32_t value);

  private:
  ::int32_t _internal_batch_size() const;
  void _internal_set_batch_size(::int32_t value);

  public:
  // int32 width = 4;
  void clear_width() ;
  ::int32_t width() const;
  void set_width(::int32_t value);

  private:
  ::int32_t _internal_width() const;
  void _internal_set_width(::int32_t value);

  public:
  // int32 height = 5;
  void clear_height() ;
  ::int32_t height() const;
  void set_height(::int32_t value);

  private:
  ::int32_t _internal_height() const;
  void _internal_set_height(::int32_t value);

  public:
  // float conf_thres = 6;
  void clear_conf_thres() ;
  float conf_thres() const;
  void set_conf_thres(float value);

  private:
  float _internal_conf_thres() const;
  void _internal_set_conf_thres(float value);

  public:
  // float iou_thres = 7;
  void clear_iou_thres() ;
  float iou_thres() const;
  void set_iou_thres(float value);

  private:
  float _internal_iou_thres() const;
  void _internal_set_iou_thres(float value);

  public:
  // int32 src_width = 9;
  void clear_src_width() ;
  ::int32_t src_width() const;
  void set_src_width(::int32_t value);

  private:
  ::int32_t _internal_src_width() const;
  void _internal_set_src_width(::int32_t value);

  public:
  // int32 src_height = 10;
  void clear_src_height() ;
  ::int32_t src_height() const;
  void set_src_height(::int32_t value);

  private:
  ::int32_t _internal_src_height() const;
  void _internal_set_src_height(::int32_t value);

  public:
  // float resize_ratio = 11;
  void clear_resize_ratio() ;
  float resize_ratio() const;
  void set_resize_ratio(float value);

  private:
  float _internal_resize_ratio() const;
  void _internal_set_resize_ratio(float value);

  public:
  // int32 dw = 12;
  void clear_dw() ;
  ::int32_t dw() const;
  void set_dw(::int32_t value);

  private:
  ::int32_t _internal_dw() const;
  void _internal_set_dw(::int32_t value);

  public:
  // int32 dh = 13;
  void clear_dh() ;
  ::int32_t dh() const;
  void set_dh(::int32_t value);

  private:
  ::int32_t _internal_dh() const;
  void _internal_set_dh(::int32_t value);

  public:
  // int32 new_unpad_w = 14;
  void clear_new_unpad_w() ;
  ::int32_t new_unpad_w() const;
  void set_new_unpad_w(::int32_t value);

  private:
  ::int32_t _internal_new_unpad_w() const;
  void _internal_set_new_unpad_w(::int32_t value);

  public:
  // int32 new_unpad_h = 15;
  void clear_new_unpad_h() ;
  ::int32_t new_unpad_h() const;
  void set_new_unpad_h(::int32_t value);

  private:
  ::int32_t _internal_new_unpad_h() const;
  void _internal_set_new_unpad_h(::int32_t value);

  public:
  // int32 max_dets = 16;
  void clear_max_dets() ;
  ::int32_t max_dets() const;
  void set_max_dets(::int32_t value);

  private:
  ::int32_t _internal_max_dets() const;
  void _internal_set_max_dets(::int32_t value);

  public:
  // int32 num_keys = 17;
  void clear_num_keys() ;
  ::int32_t num_keys() const;
  void set_num_keys(::int32_t value);

  private:
  ::int32_t _internal_num_keys() const;
  void _internal_set_num_keys(::int32_t value);

  public:
  // int32 channels = 18;
  void clear_channels() ;
  ::int32_t channels() const;
  void set_channels(::int32_t value);

  private:
  ::int32_t _internal_channels() const;
  void _internal_set_channels(::int32_t value);

  public:
  // bool run_status = 19;
  void clear_run_status() ;
  bool run_status() const;
  void set_run_status(bool value);

  private:
  bool _internal_run_status() const;
  void _internal_set_run_status(bool value);

  public:
  // @@protoc_insertion_point(class_scope:objectlocation.TaskConfig)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      5, 19, 0,
      61, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const TaskConfig& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedField<::int32_t> stride_;
    ::google::protobuf::internal::CachedSize _stride_cached_byte_size_;
    ::google::protobuf::internal::ArenaStringPtr engine_path_;
    ::int32_t num_class_;
    ::int32_t batch_size_;
    ::int32_t width_;
    ::int32_t height_;
    float conf_thres_;
    float iou_thres_;
    ::int32_t src_width_;
    ::int32_t src_height_;
    float resize_ratio_;
    ::int32_t dw_;
    ::int32_t dh_;
    ::int32_t new_unpad_w_;
    ::int32_t new_unpad_h_;
    ::int32_t max_dets_;
    ::int32_t num_keys_;
    ::int32_t channels_;
    bool run_status_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ObjectLocation_5fconf_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull TaskConfig_class_data_;
// -------------------------------------------------------------------

class ObjectLocationConfig final
    : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:objectlocation.ObjectLocationConfig) */ {
 public:
  inline ObjectLocationConfig() : ObjectLocationConfig(nullptr) {}
  ~ObjectLocationConfig() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ObjectLocationConfig* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ObjectLocationConfig));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ObjectLocationConfig(
      ::google::protobuf::internal::ConstantInitialized);

  inline ObjectLocationConfig(const ObjectLocationConfig& from) : ObjectLocationConfig(nullptr, from) {}
  inline ObjectLocationConfig(ObjectLocationConfig&& from) noexcept
      : ObjectLocationConfig(nullptr, std::move(from)) {}
  inline ObjectLocationConfig& operator=(const ObjectLocationConfig& from) {
    CopyFrom(from);
    return *this;
  }
  inline ObjectLocationConfig& operator=(ObjectLocationConfig&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ObjectLocationConfig& default_instance() {
    return *internal_default_instance();
  }
  static inline const ObjectLocationConfig* internal_default_instance() {
    return reinterpret_cast<const ObjectLocationConfig*>(
        &_ObjectLocationConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(ObjectLocationConfig& a, ObjectLocationConfig& b) { a.Swap(&b); }
  inline void Swap(ObjectLocationConfig* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ObjectLocationConfig* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ObjectLocationConfig* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ObjectLocationConfig>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ObjectLocationConfig& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ObjectLocationConfig& from) { ObjectLocationConfig::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ObjectLocationConfig* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "objectlocation.ObjectLocationConfig"; }

 protected:
  explicit ObjectLocationConfig(::google::protobuf::Arena* arena);
  ObjectLocationConfig(::google::protobuf::Arena* arena, const ObjectLocationConfig& from);
  ObjectLocationConfig(::google::protobuf::Arena* arena, ObjectLocationConfig&& from) noexcept
      : ObjectLocationConfig(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kTaskConfigFieldNumber = 1,
    kModulesConfigFieldNumber = 2,
  };
  // .objectlocation.TaskConfig task_config = 1;
  bool has_task_config() const;
  void clear_task_config() ;
  const ::objectlocation::TaskConfig& task_config() const;
  [[nodiscard]] ::objectlocation::TaskConfig* release_task_config();
  ::objectlocation::TaskConfig* mutable_task_config();
  void set_allocated_task_config(::objectlocation::TaskConfig* value);
  void unsafe_arena_set_allocated_task_config(::objectlocation::TaskConfig* value);
  ::objectlocation::TaskConfig* unsafe_arena_release_task_config();

  private:
  const ::objectlocation::TaskConfig& _internal_task_config() const;
  ::objectlocation::TaskConfig* _internal_mutable_task_config();

  public:
  // .common.ModulesConfig modules_config = 2;
  bool has_modules_config() const;
  void clear_modules_config() ;
  const ::common::ModulesConfig& modules_config() const;
  [[nodiscard]] ::common::ModulesConfig* release_modules_config();
  ::common::ModulesConfig* mutable_modules_config();
  void set_allocated_modules_config(::common::ModulesConfig* value);
  void unsafe_arena_set_allocated_modules_config(::common::ModulesConfig* value);
  ::common::ModulesConfig* unsafe_arena_release_modules_config();

  private:
  const ::common::ModulesConfig& _internal_modules_config() const;
  ::common::ModulesConfig* _internal_mutable_modules_config();

  public:
  // @@protoc_insertion_point(class_scope:objectlocation.ObjectLocationConfig)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 2,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const ObjectLocationConfig& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::objectlocation::TaskConfig* task_config_;
    ::common::ModulesConfig* modules_config_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ObjectLocation_5fconf_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull ObjectLocationConfig_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// TaskConfig

// string engine_path = 1;
inline void TaskConfig::clear_engine_path() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.engine_path_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& TaskConfig::engine_path() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:objectlocation.TaskConfig.engine_path)
  return _internal_engine_path();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void TaskConfig::set_engine_path(Arg_&& arg,
                                              Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.engine_path_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:objectlocation.TaskConfig.engine_path)
}
inline std::string* TaskConfig::mutable_engine_path() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_engine_path();
  // @@protoc_insertion_point(field_mutable:objectlocation.TaskConfig.engine_path)
  return _s;
}
inline const std::string& TaskConfig::_internal_engine_path() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.engine_path_.Get();
}
inline void TaskConfig::_internal_set_engine_path(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.engine_path_.Set(value, GetArena());
}
inline std::string* TaskConfig::_internal_mutable_engine_path() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.engine_path_.Mutable( GetArena());
}
inline std::string* TaskConfig::release_engine_path() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:objectlocation.TaskConfig.engine_path)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.engine_path_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.engine_path_.Set("", GetArena());
  }
  return released;
}
inline void TaskConfig::set_allocated_engine_path(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.engine_path_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.engine_path_.IsDefault()) {
    _impl_.engine_path_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:objectlocation.TaskConfig.engine_path)
}

// int32 num_class = 2;
inline void TaskConfig::clear_num_class() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.num_class_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline ::int32_t TaskConfig::num_class() const {
  // @@protoc_insertion_point(field_get:objectlocation.TaskConfig.num_class)
  return _internal_num_class();
}
inline void TaskConfig::set_num_class(::int32_t value) {
  _internal_set_num_class(value);
  _impl_._has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_set:objectlocation.TaskConfig.num_class)
}
inline ::int32_t TaskConfig::_internal_num_class() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.num_class_;
}
inline void TaskConfig::_internal_set_num_class(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.num_class_ = value;
}

// int32 batch_size = 3;
inline void TaskConfig::clear_batch_size() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.batch_size_ = 0;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline ::int32_t TaskConfig::batch_size() const {
  // @@protoc_insertion_point(field_get:objectlocation.TaskConfig.batch_size)
  return _internal_batch_size();
}
inline void TaskConfig::set_batch_size(::int32_t value) {
  _internal_set_batch_size(value);
  _impl_._has_bits_[0] |= 0x00000004u;
  // @@protoc_insertion_point(field_set:objectlocation.TaskConfig.batch_size)
}
inline ::int32_t TaskConfig::_internal_batch_size() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.batch_size_;
}
inline void TaskConfig::_internal_set_batch_size(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.batch_size_ = value;
}

// int32 width = 4;
inline void TaskConfig::clear_width() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.width_ = 0;
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline ::int32_t TaskConfig::width() const {
  // @@protoc_insertion_point(field_get:objectlocation.TaskConfig.width)
  return _internal_width();
}
inline void TaskConfig::set_width(::int32_t value) {
  _internal_set_width(value);
  _impl_._has_bits_[0] |= 0x00000008u;
  // @@protoc_insertion_point(field_set:objectlocation.TaskConfig.width)
}
inline ::int32_t TaskConfig::_internal_width() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.width_;
}
inline void TaskConfig::_internal_set_width(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.width_ = value;
}

// int32 height = 5;
inline void TaskConfig::clear_height() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.height_ = 0;
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline ::int32_t TaskConfig::height() const {
  // @@protoc_insertion_point(field_get:objectlocation.TaskConfig.height)
  return _internal_height();
}
inline void TaskConfig::set_height(::int32_t value) {
  _internal_set_height(value);
  _impl_._has_bits_[0] |= 0x00000010u;
  // @@protoc_insertion_point(field_set:objectlocation.TaskConfig.height)
}
inline ::int32_t TaskConfig::_internal_height() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.height_;
}
inline void TaskConfig::_internal_set_height(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.height_ = value;
}

// float conf_thres = 6;
inline void TaskConfig::clear_conf_thres() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.conf_thres_ = 0;
  _impl_._has_bits_[0] &= ~0x00000020u;
}
inline float TaskConfig::conf_thres() const {
  // @@protoc_insertion_point(field_get:objectlocation.TaskConfig.conf_thres)
  return _internal_conf_thres();
}
inline void TaskConfig::set_conf_thres(float value) {
  _internal_set_conf_thres(value);
  _impl_._has_bits_[0] |= 0x00000020u;
  // @@protoc_insertion_point(field_set:objectlocation.TaskConfig.conf_thres)
}
inline float TaskConfig::_internal_conf_thres() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.conf_thres_;
}
inline void TaskConfig::_internal_set_conf_thres(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.conf_thres_ = value;
}

// float iou_thres = 7;
inline void TaskConfig::clear_iou_thres() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.iou_thres_ = 0;
  _impl_._has_bits_[0] &= ~0x00000040u;
}
inline float TaskConfig::iou_thres() const {
  // @@protoc_insertion_point(field_get:objectlocation.TaskConfig.iou_thres)
  return _internal_iou_thres();
}
inline void TaskConfig::set_iou_thres(float value) {
  _internal_set_iou_thres(value);
  _impl_._has_bits_[0] |= 0x00000040u;
  // @@protoc_insertion_point(field_set:objectlocation.TaskConfig.iou_thres)
}
inline float TaskConfig::_internal_iou_thres() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.iou_thres_;
}
inline void TaskConfig::_internal_set_iou_thres(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.iou_thres_ = value;
}

// repeated int32 stride = 8;
inline int TaskConfig::_internal_stride_size() const {
  return _internal_stride().size();
}
inline int TaskConfig::stride_size() const {
  return _internal_stride_size();
}
inline void TaskConfig::clear_stride() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.stride_.Clear();
}
inline ::int32_t TaskConfig::stride(int index) const {
  // @@protoc_insertion_point(field_get:objectlocation.TaskConfig.stride)
  return _internal_stride().Get(index);
}
inline void TaskConfig::set_stride(int index, ::int32_t value) {
  _internal_mutable_stride()->Set(index, value);
  // @@protoc_insertion_point(field_set:objectlocation.TaskConfig.stride)
}
inline void TaskConfig::add_stride(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_stride()->Add(value);
  // @@protoc_insertion_point(field_add:objectlocation.TaskConfig.stride)
}
inline const ::google::protobuf::RepeatedField<::int32_t>& TaskConfig::stride() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:objectlocation.TaskConfig.stride)
  return _internal_stride();
}
inline ::google::protobuf::RepeatedField<::int32_t>* TaskConfig::mutable_stride()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:objectlocation.TaskConfig.stride)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_stride();
}
inline const ::google::protobuf::RepeatedField<::int32_t>&
TaskConfig::_internal_stride() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.stride_;
}
inline ::google::protobuf::RepeatedField<::int32_t>* TaskConfig::_internal_mutable_stride() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.stride_;
}

// int32 src_width = 9;
inline void TaskConfig::clear_src_width() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.src_width_ = 0;
  _impl_._has_bits_[0] &= ~0x00000080u;
}
inline ::int32_t TaskConfig::src_width() const {
  // @@protoc_insertion_point(field_get:objectlocation.TaskConfig.src_width)
  return _internal_src_width();
}
inline void TaskConfig::set_src_width(::int32_t value) {
  _internal_set_src_width(value);
  _impl_._has_bits_[0] |= 0x00000080u;
  // @@protoc_insertion_point(field_set:objectlocation.TaskConfig.src_width)
}
inline ::int32_t TaskConfig::_internal_src_width() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.src_width_;
}
inline void TaskConfig::_internal_set_src_width(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.src_width_ = value;
}

// int32 src_height = 10;
inline void TaskConfig::clear_src_height() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.src_height_ = 0;
  _impl_._has_bits_[0] &= ~0x00000100u;
}
inline ::int32_t TaskConfig::src_height() const {
  // @@protoc_insertion_point(field_get:objectlocation.TaskConfig.src_height)
  return _internal_src_height();
}
inline void TaskConfig::set_src_height(::int32_t value) {
  _internal_set_src_height(value);
  _impl_._has_bits_[0] |= 0x00000100u;
  // @@protoc_insertion_point(field_set:objectlocation.TaskConfig.src_height)
}
inline ::int32_t TaskConfig::_internal_src_height() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.src_height_;
}
inline void TaskConfig::_internal_set_src_height(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.src_height_ = value;
}

// float resize_ratio = 11;
inline void TaskConfig::clear_resize_ratio() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.resize_ratio_ = 0;
  _impl_._has_bits_[0] &= ~0x00000200u;
}
inline float TaskConfig::resize_ratio() const {
  // @@protoc_insertion_point(field_get:objectlocation.TaskConfig.resize_ratio)
  return _internal_resize_ratio();
}
inline void TaskConfig::set_resize_ratio(float value) {
  _internal_set_resize_ratio(value);
  _impl_._has_bits_[0] |= 0x00000200u;
  // @@protoc_insertion_point(field_set:objectlocation.TaskConfig.resize_ratio)
}
inline float TaskConfig::_internal_resize_ratio() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.resize_ratio_;
}
inline void TaskConfig::_internal_set_resize_ratio(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.resize_ratio_ = value;
}

// int32 dw = 12;
inline void TaskConfig::clear_dw() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.dw_ = 0;
  _impl_._has_bits_[0] &= ~0x00000400u;
}
inline ::int32_t TaskConfig::dw() const {
  // @@protoc_insertion_point(field_get:objectlocation.TaskConfig.dw)
  return _internal_dw();
}
inline void TaskConfig::set_dw(::int32_t value) {
  _internal_set_dw(value);
  _impl_._has_bits_[0] |= 0x00000400u;
  // @@protoc_insertion_point(field_set:objectlocation.TaskConfig.dw)
}
inline ::int32_t TaskConfig::_internal_dw() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.dw_;
}
inline void TaskConfig::_internal_set_dw(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.dw_ = value;
}

// int32 dh = 13;
inline void TaskConfig::clear_dh() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.dh_ = 0;
  _impl_._has_bits_[0] &= ~0x00000800u;
}
inline ::int32_t TaskConfig::dh() const {
  // @@protoc_insertion_point(field_get:objectlocation.TaskConfig.dh)
  return _internal_dh();
}
inline void TaskConfig::set_dh(::int32_t value) {
  _internal_set_dh(value);
  _impl_._has_bits_[0] |= 0x00000800u;
  // @@protoc_insertion_point(field_set:objectlocation.TaskConfig.dh)
}
inline ::int32_t TaskConfig::_internal_dh() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.dh_;
}
inline void TaskConfig::_internal_set_dh(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.dh_ = value;
}

// int32 new_unpad_w = 14;
inline void TaskConfig::clear_new_unpad_w() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.new_unpad_w_ = 0;
  _impl_._has_bits_[0] &= ~0x00001000u;
}
inline ::int32_t TaskConfig::new_unpad_w() const {
  // @@protoc_insertion_point(field_get:objectlocation.TaskConfig.new_unpad_w)
  return _internal_new_unpad_w();
}
inline void TaskConfig::set_new_unpad_w(::int32_t value) {
  _internal_set_new_unpad_w(value);
  _impl_._has_bits_[0] |= 0x00001000u;
  // @@protoc_insertion_point(field_set:objectlocation.TaskConfig.new_unpad_w)
}
inline ::int32_t TaskConfig::_internal_new_unpad_w() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.new_unpad_w_;
}
inline void TaskConfig::_internal_set_new_unpad_w(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.new_unpad_w_ = value;
}

// int32 new_unpad_h = 15;
inline void TaskConfig::clear_new_unpad_h() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.new_unpad_h_ = 0;
  _impl_._has_bits_[0] &= ~0x00002000u;
}
inline ::int32_t TaskConfig::new_unpad_h() const {
  // @@protoc_insertion_point(field_get:objectlocation.TaskConfig.new_unpad_h)
  return _internal_new_unpad_h();
}
inline void TaskConfig::set_new_unpad_h(::int32_t value) {
  _internal_set_new_unpad_h(value);
  _impl_._has_bits_[0] |= 0x00002000u;
  // @@protoc_insertion_point(field_set:objectlocation.TaskConfig.new_unpad_h)
}
inline ::int32_t TaskConfig::_internal_new_unpad_h() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.new_unpad_h_;
}
inline void TaskConfig::_internal_set_new_unpad_h(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.new_unpad_h_ = value;
}

// int32 max_dets = 16;
inline void TaskConfig::clear_max_dets() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.max_dets_ = 0;
  _impl_._has_bits_[0] &= ~0x00004000u;
}
inline ::int32_t TaskConfig::max_dets() const {
  // @@protoc_insertion_point(field_get:objectlocation.TaskConfig.max_dets)
  return _internal_max_dets();
}
inline void TaskConfig::set_max_dets(::int32_t value) {
  _internal_set_max_dets(value);
  _impl_._has_bits_[0] |= 0x00004000u;
  // @@protoc_insertion_point(field_set:objectlocation.TaskConfig.max_dets)
}
inline ::int32_t TaskConfig::_internal_max_dets() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.max_dets_;
}
inline void TaskConfig::_internal_set_max_dets(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.max_dets_ = value;
}

// int32 num_keys = 17;
inline void TaskConfig::clear_num_keys() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.num_keys_ = 0;
  _impl_._has_bits_[0] &= ~0x00008000u;
}
inline ::int32_t TaskConfig::num_keys() const {
  // @@protoc_insertion_point(field_get:objectlocation.TaskConfig.num_keys)
  return _internal_num_keys();
}
inline void TaskConfig::set_num_keys(::int32_t value) {
  _internal_set_num_keys(value);
  _impl_._has_bits_[0] |= 0x00008000u;
  // @@protoc_insertion_point(field_set:objectlocation.TaskConfig.num_keys)
}
inline ::int32_t TaskConfig::_internal_num_keys() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.num_keys_;
}
inline void TaskConfig::_internal_set_num_keys(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.num_keys_ = value;
}

// int32 channels = 18;
inline void TaskConfig::clear_channels() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.channels_ = 0;
  _impl_._has_bits_[0] &= ~0x00010000u;
}
inline ::int32_t TaskConfig::channels() const {
  // @@protoc_insertion_point(field_get:objectlocation.TaskConfig.channels)
  return _internal_channels();
}
inline void TaskConfig::set_channels(::int32_t value) {
  _internal_set_channels(value);
  _impl_._has_bits_[0] |= 0x00010000u;
  // @@protoc_insertion_point(field_set:objectlocation.TaskConfig.channels)
}
inline ::int32_t TaskConfig::_internal_channels() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.channels_;
}
inline void TaskConfig::_internal_set_channels(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.channels_ = value;
}

// bool run_status = 19;
inline void TaskConfig::clear_run_status() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.run_status_ = false;
  _impl_._has_bits_[0] &= ~0x00020000u;
}
inline bool TaskConfig::run_status() const {
  // @@protoc_insertion_point(field_get:objectlocation.TaskConfig.run_status)
  return _internal_run_status();
}
inline void TaskConfig::set_run_status(bool value) {
  _internal_set_run_status(value);
  _impl_._has_bits_[0] |= 0x00020000u;
  // @@protoc_insertion_point(field_set:objectlocation.TaskConfig.run_status)
}
inline bool TaskConfig::_internal_run_status() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.run_status_;
}
inline void TaskConfig::_internal_set_run_status(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.run_status_ = value;
}

// -------------------------------------------------------------------

// ObjectLocationConfig

// .objectlocation.TaskConfig task_config = 1;
inline bool ObjectLocationConfig::has_task_config() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.task_config_ != nullptr);
  return value;
}
inline void ObjectLocationConfig::clear_task_config() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.task_config_ != nullptr) _impl_.task_config_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::objectlocation::TaskConfig& ObjectLocationConfig::_internal_task_config() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::objectlocation::TaskConfig* p = _impl_.task_config_;
  return p != nullptr ? *p : reinterpret_cast<const ::objectlocation::TaskConfig&>(::objectlocation::_TaskConfig_default_instance_);
}
inline const ::objectlocation::TaskConfig& ObjectLocationConfig::task_config() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:objectlocation.ObjectLocationConfig.task_config)
  return _internal_task_config();
}
inline void ObjectLocationConfig::unsafe_arena_set_allocated_task_config(::objectlocation::TaskConfig* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.task_config_);
  }
  _impl_.task_config_ = reinterpret_cast<::objectlocation::TaskConfig*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:objectlocation.ObjectLocationConfig.task_config)
}
inline ::objectlocation::TaskConfig* ObjectLocationConfig::release_task_config() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::objectlocation::TaskConfig* released = _impl_.task_config_;
  _impl_.task_config_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::objectlocation::TaskConfig* ObjectLocationConfig::unsafe_arena_release_task_config() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:objectlocation.ObjectLocationConfig.task_config)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::objectlocation::TaskConfig* temp = _impl_.task_config_;
  _impl_.task_config_ = nullptr;
  return temp;
}
inline ::objectlocation::TaskConfig* ObjectLocationConfig::_internal_mutable_task_config() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.task_config_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::objectlocation::TaskConfig>(GetArena());
    _impl_.task_config_ = reinterpret_cast<::objectlocation::TaskConfig*>(p);
  }
  return _impl_.task_config_;
}
inline ::objectlocation::TaskConfig* ObjectLocationConfig::mutable_task_config() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::objectlocation::TaskConfig* _msg = _internal_mutable_task_config();
  // @@protoc_insertion_point(field_mutable:objectlocation.ObjectLocationConfig.task_config)
  return _msg;
}
inline void ObjectLocationConfig::set_allocated_task_config(::objectlocation::TaskConfig* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete (_impl_.task_config_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = (value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.task_config_ = reinterpret_cast<::objectlocation::TaskConfig*>(value);
  // @@protoc_insertion_point(field_set_allocated:objectlocation.ObjectLocationConfig.task_config)
}

// .common.ModulesConfig modules_config = 2;
inline bool ObjectLocationConfig::has_modules_config() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.modules_config_ != nullptr);
  return value;
}
inline const ::common::ModulesConfig& ObjectLocationConfig::_internal_modules_config() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::common::ModulesConfig* p = _impl_.modules_config_;
  return p != nullptr ? *p : reinterpret_cast<const ::common::ModulesConfig&>(::common::_ModulesConfig_default_instance_);
}
inline const ::common::ModulesConfig& ObjectLocationConfig::modules_config() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:objectlocation.ObjectLocationConfig.modules_config)
  return _internal_modules_config();
}
inline void ObjectLocationConfig::unsafe_arena_set_allocated_modules_config(::common::ModulesConfig* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.modules_config_);
  }
  _impl_.modules_config_ = reinterpret_cast<::common::ModulesConfig*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:objectlocation.ObjectLocationConfig.modules_config)
}
inline ::common::ModulesConfig* ObjectLocationConfig::release_modules_config() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::common::ModulesConfig* released = _impl_.modules_config_;
  _impl_.modules_config_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::common::ModulesConfig* ObjectLocationConfig::unsafe_arena_release_modules_config() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:objectlocation.ObjectLocationConfig.modules_config)

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::common::ModulesConfig* temp = _impl_.modules_config_;
  _impl_.modules_config_ = nullptr;
  return temp;
}
inline ::common::ModulesConfig* ObjectLocationConfig::_internal_mutable_modules_config() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.modules_config_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::common::ModulesConfig>(GetArena());
    _impl_.modules_config_ = reinterpret_cast<::common::ModulesConfig*>(p);
  }
  return _impl_.modules_config_;
}
inline ::common::ModulesConfig* ObjectLocationConfig::mutable_modules_config() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000002u;
  ::common::ModulesConfig* _msg = _internal_mutable_modules_config();
  // @@protoc_insertion_point(field_mutable:objectlocation.ObjectLocationConfig.modules_config)
  return _msg;
}
inline void ObjectLocationConfig::set_allocated_modules_config(::common::ModulesConfig* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.modules_config_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }

  _impl_.modules_config_ = reinterpret_cast<::common::ModulesConfig*>(value);
  // @@protoc_insertion_point(field_set_allocated:objectlocation.ObjectLocationConfig.modules_config)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace objectlocation


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // ObjectLocation_5fconf_2eproto_2epb_2eh
