/*******************************************************
 文件：CMultiModalData.idl
 作者：
 描述：多模态视频的原始数据结构体
 版本：v1.0
 日期：2025-04-18
 *******************************************************/

#include "CDataBase.idl"

//单路视频结果结构体
struct CVideoSrcData : CDataBase
{
	octet 					ucCameraId;				//相机编号
	unsigned short 			usBmpLength;			//图片长度
	unsigned short 			usBmpWidth;				//图片宽度
	unsigned long 			unBmpBytes;				//图片数据字节长度
	sequence<octet> 		vecImageBuf;			//获取的相机数据，是libav输出的图像数据，uinit8类型的数组，数组大小由图片宽高决定
};

// 视差图信息
struct CDisparityResult {
    unsigned short          usWidth;                
	// 视差图宽度
    unsigned short          usHeight;               // 视差图高度
    sequence<long>         vecDistanceInfo;        // 所有像素的位置信息
};

// 时间匹配好的视频数据结构体
struct CMultiModalSrcData : CDataBase
{   
	sequence<CVideoSrcData>  vecVideoSrcData;		    // 与时间匹配好的每一路相机数据（0为双目图像，1为红外图像）
    sequence<float>          vecfHomography;            // 双目图像和红外图像之间的单应性矩阵(3x3)
	CDisparityResult   		 tDisparityResult; 		    // 视差图结果
};