// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file counter_response_message.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef _FAST_DDS_GENERATED_COUNTER_RESPONSE_MESSAGE_H_
#define _FAST_DDS_GENERATED_COUNTER_RESPONSE_MESSAGE_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <map>
#include <string>
#include <vector>

#include <fastcdr/cdr/fixed_size_string.hpp>
#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>



#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(COUNTER_RESPONSE_MESSAGE_SOURCE)
#define COUNTER_RESPONSE_MESSAGE_DllAPI __declspec( dllexport )
#else
#define COUNTER_RESPONSE_MESSAGE_DllAPI __declspec( dllimport )
#endif // COUNTER_RESPONSE_MESSAGE_SOURCE
#else
#define COUNTER_RESPONSE_MESSAGE_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define COUNTER_RESPONSE_MESSAGE_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
} // namespace fastcdr
} // namespace eprosima





/*!
 * @brief This class represents the structure CounterResponseMessage defined by the user in the IDL file.
 * @ingroup counter_response_message
 */
class CounterResponseMessage
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport CounterResponseMessage();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~CounterResponseMessage();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object CounterResponseMessage that will be copied.
     */
    eProsima_user_DllExport CounterResponseMessage(
            const CounterResponseMessage& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object CounterResponseMessage that will be copied.
     */
    eProsima_user_DllExport CounterResponseMessage(
            CounterResponseMessage&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object CounterResponseMessage that will be copied.
     */
    eProsima_user_DllExport CounterResponseMessage& operator =(
            const CounterResponseMessage& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object CounterResponseMessage that will be copied.
     */
    eProsima_user_DllExport CounterResponseMessage& operator =(
            CounterResponseMessage&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x CounterResponseMessage object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const CounterResponseMessage& x) const;

    /*!
     * @brief Comparison operator.
     * @param x CounterResponseMessage object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const CounterResponseMessage& x) const;

    /*!
     * @brief This function sets a value in member cnt
     * @param _cnt New value for member cnt
     */
    eProsima_user_DllExport void cnt(
            int32_t _cnt);

    /*!
     * @brief This function returns the value of member cnt
     * @return Value of member cnt
     */
    eProsima_user_DllExport int32_t cnt() const;

    /*!
     * @brief This function returns a reference to member cnt
     * @return Reference to member cnt
     */
    eProsima_user_DllExport int32_t& cnt();


    /*!
     * @brief This function copies the value in member response
     * @param _response New value to be copied in member response
     */
    eProsima_user_DllExport void response(
            const std::string& _response);

    /*!
     * @brief This function moves the value in member response
     * @param _response New value to be moved in member response
     */
    eProsima_user_DllExport void response(
            std::string&& _response);

    /*!
     * @brief This function returns a constant reference to member response
     * @return Constant reference to member response
     */
    eProsima_user_DllExport const std::string& response() const;

    /*!
     * @brief This function returns a reference to member response
     * @return Reference to member response
     */
    eProsima_user_DllExport std::string& response();

private:

    int32_t m_cnt{0};
    std::string m_response;

};

#endif // _FAST_DDS_GENERATED_COUNTER_RESPONSE_MESSAGE_H_



